// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: address.sql

package store

import (
	"context"
)

const createAddress = `-- name: CreateAddress :one

INSERT INTO address (alias, address, location, "userId")
VALUES ($1, $2, point($3, $4), $5)
RETURNING id, alias, address,
          location[0]::float8 AS latitude,
          location[1]::float8 AS longitude
`

type CreateAddressParams struct {
	Alias   string  `json:"alias"`
	Address string  `json:"address"`
	Point   float64 `json:"point"`
	Point_2 float64 `json:"point_2"`
	UserId  *int32  `json:"userId"`
}

type CreateAddressRow struct {
	ID        int32   `json:"id"`
	Alias     string  `json:"alias"`
	Address   string  `json:"address"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

// Direcciones del cliente. TypeORM aplicaba soft-delete (columna deletedAt),
// por lo que las lecturas filtran deletedAt IS NULL.
func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (CreateAddressRow, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.Alias,
		arg.Address,
		arg.Point,
		arg.Point_2,
		arg.UserId,
	)
	var i CreateAddressRow
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, alias, address,
       location[0]::float8 AS latitude,
       location[1]::float8 AS longitude
FROM address
WHERE id = $1 AND "deletedAt" IS NULL
`

type GetAddressByIDRow struct {
	ID        int32   `json:"id"`
	Alias     string  `json:"alias"`
	Address   string  `json:"address"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

func (q *Queries) GetAddressByID(ctx context.Context, id int32) (GetAddressByIDRow, error) {
	row := q.db.QueryRow(ctx, getAddressByID, id)
	var i GetAddressByIDRow
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const listAddressesByUser = `-- name: ListAddressesByUser :many
SELECT id, alias, address,
       location[0]::float8 AS latitude,
       location[1]::float8 AS longitude
FROM address
WHERE "userId" = $1 AND "deletedAt" IS NULL
ORDER BY id
`

type ListAddressesByUserRow struct {
	ID        int32   `json:"id"`
	Alias     string  `json:"alias"`
	Address   string  `json:"address"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

func (q *Queries) ListAddressesByUser(ctx context.Context, userid *int32) ([]ListAddressesByUserRow, error) {
	rows, err := q.db.Query(ctx, listAddressesByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAddressesByUserRow{}
	for rows.Next() {
		var i ListAddressesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAddress = `-- name: SoftDeleteAddress :execrows
UPDATE address
SET "deletedAt" = now()
WHERE id = $1 AND "deletedAt" IS NULL
`

func (q *Queries) SoftDeleteAddress(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAddress, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE address
SET alias = $2, address = $3, location = point($4, $5),
    "deletedAt" = NULL, "updatedAt" = now()
WHERE id = $1 AND "deletedAt" IS NULL
RETURNING id, alias, address,
          location[0]::float8 AS latitude,
          location[1]::float8 AS longitude
`

type UpdateAddressParams struct {
	ID      int32   `json:"id"`
	Alias   string  `json:"alias"`
	Address string  `json:"address"`
	Point   float64 `json:"point"`
	Point_2 float64 `json:"point_2"`
}

type UpdateAddressRow struct {
	ID        int32   `json:"id"`
	Alias     string  `json:"alias"`
	Address   string  `json:"address"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (UpdateAddressRow, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.ID,
		arg.Alias,
		arg.Address,
		arg.Point,
		arg.Point_2,
	)
	var i UpdateAddressRow
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}
