// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balance.sql

package store

import (
	"context"
)

const getBalanceByUser = `-- name: GetBalanceByUser :one

SELECT "userId", balance, profit, amount, money, "createdAt", "updatedAt"
FROM balance
WHERE "userId" = $1
`

// Saldos. La tabla balance tiene como clave primaria userId.
func (q *Queries) GetBalanceByUser(ctx context.Context, userid int32) (Balance, error) {
	row := q.db.QueryRow(ctx, getBalanceByUser, userid)
	var i Balance
	err := row.Scan(
		&i.UserId,
		&i.Balance,
		&i.Profit,
		&i.Amount,
		&i.Money,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBalanceMoney = `-- name: UpdateBalanceMoney :execrows
UPDATE balance
SET money = $2, "updatedAt" = now()
WHERE "userId" = $1
`

type UpdateBalanceMoneyParams struct {
	UserId int32   `json:"userId"`
	Money  float64 `json:"money"`
}

func (q *Queries) UpdateBalanceMoney(ctx context.Context, arg UpdateBalanceMoneyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBalanceMoney, arg.UserId, arg.Money)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertBalance = `-- name: UpsertBalance :exec
INSERT INTO balance ("userId") VALUES ($1)
ON CONFLICT ("userId") DO NOTHING
`

func (q *Queries) UpsertBalance(ctx context.Context, userid int32) error {
	_, err := q.db.Exec(ctx, upsertBalance, userid)
	return err
}
