// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package store

import (
	"context"
)

const addUserRole = `-- name: AddUserRole :execrows
UPDATE "user"
SET roles = array_append(roles, $2), "updatedAt" = now()
WHERE id = $1 AND NOT ($2 = ANY(roles))
`

type AddUserRoleParams struct {
	ID          int32       `json:"id"`
	ArrayAppend interface{} `json:"array_append"`
}

// Agrega el rol solo si no lo tiene (equivalente al update de EnrollmentService).
func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, addUserRole, arg.ID, arg.ArrayAppend)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO category (name, image)
VALUES ($1, $2)
RETURNING id, name, image, "createdAt", "updatedAt"
`

type CreateCategoryParams struct {
	Name  string `json:"name"`
	Image string `json:"image"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Image)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, image, "createdAt", "updatedAt"
FROM category
WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many

SELECT id, name, image, "createdAt", "updatedAt"
FROM category
ORDER BY name ASC
`

// Categorias.
func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesPaged = `-- name: ListCategoriesPaged :many
SELECT id, name, image, "createdAt", "updatedAt"
FROM category
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListCategoriesPagedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCategoriesPaged(ctx context.Context, arg ListCategoriesPagedParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesPaged, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE category
SET name = $2, image = $3, "updatedAt" = now()
WHERE id = $1
RETURNING id, name, image, "createdAt", "updatedAt"
`

type UpdateCategoryParams struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Image string `json:"image"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.Name, arg.Image)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
