// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chat (message, type, status, "fromId", "toId", "orderId")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, message, type, status, "createdAt", "fromId", "toId", "orderId"
`

type CreateChatParams struct {
	Message string `json:"message"`
	Type    int16  `json:"type"`
	Status  int16  `json:"status"`
	FromId  int32  `json:"fromId"`
	ToId    *int32 `json:"toId"`
	OrderId int32  `json:"orderId"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat,
		arg.Message,
		arg.Type,
		arg.Status,
		arg.FromId,
		arg.ToId,
		arg.OrderId,
	)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.FromId,
		&i.ToId,
		&i.OrderId,
	)
	return i, err
}

const incrementOrderNotificationsClient = `-- name: IncrementOrderNotificationsClient :exec
UPDATE "order"
SET "notificationsClient" = "notificationsClient" + 1
WHERE id = $1
`

func (q *Queries) IncrementOrderNotificationsClient(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementOrderNotificationsClient, id)
	return err
}

const incrementOrderNotificationsDeliveryman = `-- name: IncrementOrderNotificationsDeliveryman :exec
UPDATE "order"
SET "notificationsDeliveryman" = "notificationsDeliveryman" + 1
WHERE id = $1
`

func (q *Queries) IncrementOrderNotificationsDeliveryman(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementOrderNotificationsDeliveryman, id)
	return err
}

const listChatsByOrder = `-- name: ListChatsByOrder :many

SELECT c.id, c.message, c.type, c.status, c."createdAt", c."fromId"
FROM chat c
WHERE c."orderId" = $1
ORDER BY c.id DESC
`

type ListChatsByOrderRow struct {
	ID        int32              `json:"id"`
	Message   string             `json:"message"`
	Type      int16              `json:"type"`
	Status    int16              `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	FromId    int32              `json:"fromId"`
}

// Mensajes de chat por pedido.
// La consulta original selecciona solo estos campos y ordena por id DESC.
func (q *Queries) ListChatsByOrder(ctx context.Context, orderid int32) ([]ListChatsByOrderRow, error) {
	rows, err := q.db.Query(ctx, listChatsByOrder, orderid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChatsByOrderRow{}
	for rows.Next() {
		var i ListChatsByOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
			&i.FromId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetOrderNotificationsClient = `-- name: ResetOrderNotificationsClient :exec
UPDATE "order" SET "notificationsClient" = 0 WHERE id = $1
`

func (q *Queries) ResetOrderNotificationsClient(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, resetOrderNotificationsClient, id)
	return err
}

const resetOrderNotificationsDeliveryman = `-- name: ResetOrderNotificationsDeliveryman :exec
UPDATE "order" SET "notificationsDeliveryman" = 0 WHERE id = $1
`

func (q *Queries) ResetOrderNotificationsDeliveryman(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, resetOrderNotificationsDeliveryman, id)
	return err
}
