// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company_category.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompanyCategory = `-- name: CreateCompanyCategory :one

INSERT INTO company_category ("companyId", "categoryId")
VALUES ($1, $2)
RETURNING id, "updatedAt", "companyId", "categoryId"
`

type CreateCompanyCategoryParams struct {
	CompanyId  int32 `json:"companyId"`
	CategoryId int32 `json:"categoryId"`
}

// Relacion empresa-categoria.
func (q *Queries) CreateCompanyCategory(ctx context.Context, arg CreateCompanyCategoryParams) (CompanyCategory, error) {
	row := q.db.QueryRow(ctx, createCompanyCategory, arg.CompanyId, arg.CategoryId)
	var i CompanyCategory
	err := row.Scan(
		&i.ID,
		&i.UpdatedAt,
		&i.CompanyId,
		&i.CategoryId,
	)
	return i, err
}

const deleteCompanyCategory = `-- name: DeleteCompanyCategory :execrows
DELETE FROM company_category
WHERE id = $1 AND "companyId" = $2 AND "categoryId" = $3
`

type DeleteCompanyCategoryParams struct {
	ID         int32 `json:"id"`
	CompanyId  int32 `json:"companyId"`
	CategoryId int32 `json:"categoryId"`
}

func (q *Queries) DeleteCompanyCategory(ctx context.Context, arg DeleteCompanyCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompanyCategory, arg.ID, arg.CompanyId, arg.CategoryId)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCompanyCategoriesByCompany = `-- name: ListCompanyCategoriesByCompany :many
SELECT cc.id, cc."updatedAt", cc."companyId", cc."categoryId",
       cat.id AS category_id, cat.name AS category_name, cat.image AS category_image,
       cat."createdAt" AS category_created_at, cat."updatedAt" AS category_updated_at
FROM company_category cc
INNER JOIN category cat ON cat.id = cc."categoryId"
WHERE cc."companyId" = $1
ORDER BY cc.id
LIMIT $2 OFFSET $3
`

type ListCompanyCategoriesByCompanyParams struct {
	CompanyId int32 `json:"companyId"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListCompanyCategoriesByCompanyRow struct {
	ID                int32              `json:"id"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
	CompanyId         int32              `json:"companyId"`
	CategoryId        int32              `json:"categoryId"`
	CategoryID        int32              `json:"category_id"`
	CategoryName      string             `json:"category_name"`
	CategoryImage     string             `json:"category_image"`
	CategoryCreatedAt pgtype.Timestamptz `json:"category_created_at"`
	CategoryUpdatedAt pgtype.Timestamptz `json:"category_updated_at"`
}

func (q *Queries) ListCompanyCategoriesByCompany(ctx context.Context, arg ListCompanyCategoriesByCompanyParams) ([]ListCompanyCategoriesByCompanyRow, error) {
	rows, err := q.db.Query(ctx, listCompanyCategoriesByCompany, arg.CompanyId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompanyCategoriesByCompanyRow{}
	for rows.Next() {
		var i ListCompanyCategoriesByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.UpdatedAt,
			&i.CompanyId,
			&i.CategoryId,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryImage,
			&i.CategoryCreatedAt,
			&i.CategoryUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
