// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO company (name, address, contact, image, marker, email, location, "userId")
VALUES ($1, $2, $3, $4, $5, $6, point($7, $8), $9)
RETURNING id, name, address, contact, image, marker, email,
          location[0]::float8 AS latitude,
          location[1]::float8 AS longitude,
          "createdAt", "updatedAt", "userId"
`

type CreateCompanyParams struct {
	Name    string  `json:"name"`
	Address string  `json:"address"`
	Contact string  `json:"contact"`
	Image   string  `json:"image"`
	Marker  string  `json:"marker"`
	Email   string  `json:"email"`
	Point   float64 `json:"point"`
	Point_2 float64 `json:"point_2"`
	UserId  *int32  `json:"userId"`
}

type CreateCompanyRow struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Address   string             `json:"address"`
	Contact   string             `json:"contact"`
	Image     string             `json:"image"`
	Marker    string             `json:"marker"`
	Email     string             `json:"email"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	UserId    *int32             `json:"userId"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (CreateCompanyRow, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.Name,
		arg.Address,
		arg.Contact,
		arg.Image,
		arg.Marker,
		arg.Email,
		arg.Point,
		arg.Point_2,
		arg.UserId,
	)
	var i CreateCompanyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Contact,
		&i.Image,
		&i.Marker,
		&i.Email,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserId,
	)
	return i, err
}

const findCompanyByTerm = `-- name: FindCompanyByTerm :one
SELECT id, name, address, contact, image, marker, email,
       location[0]::float8 AS latitude,
       location[1]::float8 AS longitude,
       "createdAt", "updatedAt", "userId"
FROM company
WHERE name = $1 OR address LIKE '%' || $1 || '%'
LIMIT 1
`

type FindCompanyByTermRow struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Address   string             `json:"address"`
	Contact   string             `json:"contact"`
	Image     string             `json:"image"`
	Marker    string             `json:"marker"`
	Email     string             `json:"email"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	UserId    *int32             `json:"userId"`
}

func (q *Queries) FindCompanyByTerm(ctx context.Context, name string) (FindCompanyByTermRow, error) {
	row := q.db.QueryRow(ctx, findCompanyByTerm, name)
	var i FindCompanyByTermRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Contact,
		&i.Image,
		&i.Marker,
		&i.Email,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserId,
	)
	return i, err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, name, address, contact, image, marker, email,
       location[0]::float8 AS latitude,
       location[1]::float8 AS longitude,
       "createdAt", "updatedAt", "userId"
FROM company
WHERE id = $1
`

type GetCompanyByIDRow struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Address   string             `json:"address"`
	Contact   string             `json:"contact"`
	Image     string             `json:"image"`
	Marker    string             `json:"marker"`
	Email     string             `json:"email"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	UserId    *int32             `json:"userId"`
}

func (q *Queries) GetCompanyByID(ctx context.Context, id int32) (GetCompanyByIDRow, error) {
	row := q.db.QueryRow(ctx, getCompanyByID, id)
	var i GetCompanyByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Contact,
		&i.Image,
		&i.Marker,
		&i.Email,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserId,
	)
	return i, err
}

const getCompanyByNameUpper = `-- name: GetCompanyByNameUpper :one

SELECT id, name, address, contact, image, marker, email,
       location[0]::float8 AS latitude,
       location[1]::float8 AS longitude,
       "createdAt", "updatedAt", "userId"
FROM company
WHERE UPPER(name) = UPPER($1)
`

type GetCompanyByNameUpperRow struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Address   string             `json:"address"`
	Contact   string             `json:"contact"`
	Image     string             `json:"image"`
	Marker    string             `json:"marker"`
	Email     string             `json:"email"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	UserId    *int32             `json:"userId"`
}

// Empresas (comercios). Usado por manager/enrollment y, mas adelante, por admin.
func (q *Queries) GetCompanyByNameUpper(ctx context.Context, upper interface{}) (GetCompanyByNameUpperRow, error) {
	row := q.db.QueryRow(ctx, getCompanyByNameUpper, upper)
	var i GetCompanyByNameUpperRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Contact,
		&i.Image,
		&i.Marker,
		&i.Email,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserId,
	)
	return i, err
}

const hardDeleteCompany = `-- name: HardDeleteCompany :execrows
DELETE FROM company WHERE id = $1
`

// La entidad Company NO tiene columna deletedAt, por lo que el softDelete
// original de NestJS no tenia columna que escribir. Se hace borrado real.
func (q *Queries) HardDeleteCompany(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteCompany, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, address, contact, image, marker, email,
       location[0]::float8 AS latitude,
       location[1]::float8 AS longitude,
       "createdAt", "updatedAt", "userId"
FROM company
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListCompaniesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListCompaniesRow struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Address   string             `json:"address"`
	Contact   string             `json:"contact"`
	Image     string             `json:"image"`
	Marker    string             `json:"marker"`
	Email     string             `json:"email"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	UserId    *int32             `json:"userId"`
}

func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]ListCompaniesRow, error) {
	rows, err := q.db.Query(ctx, listCompanies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompaniesRow{}
	for rows.Next() {
		var i ListCompaniesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Contact,
			&i.Image,
			&i.Marker,
			&i.Email,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE company
SET name = $2, address = $3, contact = $4, image = $5, marker = $6, email = $7,
    location = point($8, $9), "updatedAt" = now()
WHERE id = $1
RETURNING id, name, address, contact, image, marker, email,
          location[0]::float8 AS latitude,
          location[1]::float8 AS longitude,
          "createdAt", "updatedAt", "userId"
`

type UpdateCompanyParams struct {
	ID      int32   `json:"id"`
	Name    string  `json:"name"`
	Address string  `json:"address"`
	Contact string  `json:"contact"`
	Image   string  `json:"image"`
	Marker  string  `json:"marker"`
	Email   string  `json:"email"`
	Point   float64 `json:"point"`
	Point_2 float64 `json:"point_2"`
}

type UpdateCompanyRow struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Address   string             `json:"address"`
	Contact   string             `json:"contact"`
	Image     string             `json:"image"`
	Marker    string             `json:"marker"`
	Email     string             `json:"email"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	UserId    *int32             `json:"userId"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (UpdateCompanyRow, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Contact,
		arg.Image,
		arg.Marker,
		arg.Email,
		arg.Point,
		arg.Point_2,
	)
	var i UpdateCompanyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Contact,
		&i.Image,
		&i.Marker,
		&i.Email,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserId,
	)
	return i, err
}
