// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credit.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addBalanceAmount = `-- name: AddBalanceAmount :exec
INSERT INTO balance ("userId", balance)
VALUES ($1, $2)
ON CONFLICT ("userId") DO UPDATE
SET balance = balance.balance + EXCLUDED.balance, "updatedAt" = now()
`

type AddBalanceAmountParams struct {
	UserId  int32   `json:"userId"`
	Balance float64 `json:"balance"`
}

// Suma al balance del repartidor, creando el registro si no existe.
func (q *Queries) AddBalanceAmount(ctx context.Context, arg AddBalanceAmountParams) error {
	_, err := q.db.Exec(ctx, addBalanceAmount, arg.UserId, arg.Balance)
	return err
}

const createCredit = `-- name: CreateCredit :one
INSERT INTO credit (amount, "deliverymanId")
VALUES ($1, $2)
RETURNING id, amount, "createdAt", "deliverymanId"
`

type CreateCreditParams struct {
	Amount        float64 `json:"amount"`
	DeliverymanId *int32  `json:"deliverymanId"`
}

func (q *Queries) CreateCredit(ctx context.Context, arg CreateCreditParams) (Credit, error) {
	row := q.db.QueryRow(ctx, createCredit, arg.Amount, arg.DeliverymanId)
	var i Credit
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.CreatedAt,
		&i.DeliverymanId,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one

SELECT id, "idGoogle", "fullName", email, phone, image, "isActive", roles,
       "createdAt", "updatedAt"
FROM "user"
WHERE phone = $1
`

type GetUserByPhoneRow struct {
	ID        int32              `json:"id"`
	IdGoogle  *string            `json:"idGoogle"`
	FullName  string             `json:"fullName"`
	Email     string             `json:"email"`
	Phone     *string            `json:"phone"`
	Image     string             `json:"image"`
	IsActive  bool               `json:"isActive"`
	Roles     []string           `json:"roles"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

// Creditos: recarga de saldo que hace un admin al repartidor.
func (q *Queries) GetUserByPhone(ctx context.Context, phone *string) (GetUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i GetUserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.IdGoogle,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Image,
		&i.IsActive,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
