// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hours.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHoursOperation = `-- name: CreateHoursOperation :one

INSERT INTO hours_operation (day, "storeId")
VALUES ($1, $2)
RETURNING id, day, open, close, "timeZone", "storeId"
`

type CreateHoursOperationParams struct {
	Day     int16  `json:"day"`
	StoreId *int32 `json:"storeId"`
}

// Horarios de atencion por tienda.
func (q *Queries) CreateHoursOperation(ctx context.Context, arg CreateHoursOperationParams) (HoursOperation, error) {
	row := q.db.QueryRow(ctx, createHoursOperation, arg.Day, arg.StoreId)
	var i HoursOperation
	err := row.Scan(
		&i.ID,
		&i.Day,
		&i.Open,
		&i.Close,
		&i.TimeZone,
		&i.StoreId,
	)
	return i, err
}

const createHoursOperationFull = `-- name: CreateHoursOperationFull :one
INSERT INTO hours_operation (day, open, close, "storeId")
VALUES ($1, $2, $3, $4)
RETURNING id, day, open, close, "timeZone", "storeId"
`

type CreateHoursOperationFullParams struct {
	Day     int16       `json:"day"`
	Open    pgtype.Time `json:"open"`
	Close   pgtype.Time `json:"close"`
	StoreId *int32      `json:"storeId"`
}

func (q *Queries) CreateHoursOperationFull(ctx context.Context, arg CreateHoursOperationFullParams) (HoursOperation, error) {
	row := q.db.QueryRow(ctx, createHoursOperationFull,
		arg.Day,
		arg.Open,
		arg.Close,
		arg.StoreId,
	)
	var i HoursOperation
	err := row.Scan(
		&i.ID,
		&i.Day,
		&i.Open,
		&i.Close,
		&i.TimeZone,
		&i.StoreId,
	)
	return i, err
}

const getHoursOperationByID = `-- name: GetHoursOperationByID :one
SELECT id, day, open, close, "timeZone", "storeId"
FROM hours_operation
WHERE id = $1
`

func (q *Queries) GetHoursOperationByID(ctx context.Context, id int32) (HoursOperation, error) {
	row := q.db.QueryRow(ctx, getHoursOperationByID, id)
	var i HoursOperation
	err := row.Scan(
		&i.ID,
		&i.Day,
		&i.Open,
		&i.Close,
		&i.TimeZone,
		&i.StoreId,
	)
	return i, err
}

const listHoursByStore = `-- name: ListHoursByStore :many
SELECT id, day, open, close, "timeZone", "storeId"
FROM hours_operation
WHERE "storeId" = $1
ORDER BY day ASC
`

func (q *Queries) ListHoursByStore(ctx context.Context, storeid *int32) ([]HoursOperation, error) {
	rows, err := q.db.Query(ctx, listHoursByStore, storeid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HoursOperation{}
	for rows.Next() {
		var i HoursOperation
		if err := rows.Scan(
			&i.ID,
			&i.Day,
			&i.Open,
			&i.Close,
			&i.TimeZone,
			&i.StoreId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHoursOperation = `-- name: UpdateHoursOperation :one
UPDATE hours_operation
SET open = $2, close = $3
WHERE id = $1
RETURNING id, day, open, close, "timeZone", "storeId"
`

type UpdateHoursOperationParams struct {
	ID    int32       `json:"id"`
	Open  pgtype.Time `json:"open"`
	Close pgtype.Time `json:"close"`
}

func (q *Queries) UpdateHoursOperation(ctx context.Context, arg UpdateHoursOperationParams) (HoursOperation, error) {
	row := q.db.QueryRow(ctx, updateHoursOperation, arg.ID, arg.Open, arg.Close)
	var i HoursOperation
	err := row.Scan(
		&i.ID,
		&i.Day,
		&i.Open,
		&i.Close,
		&i.TimeZone,
		&i.StoreId,
	)
	return i, err
}
