// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: market.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO "order" (
    note, address, status, products, "deliveryFee", total, payment,
    location, "orderedAt", "storeId", "userId"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, point($8, $9), $10, $11, $12
)
RETURNING id, note, address, status, products, "deliveryFee", total, payment,
          "scoreClient", "scoreDeliveryman", "notificationsClient",
          "notificationsDeliveryman", "orderedAt", "createdAt",
          location[0]::float8 AS latitude, location[1]::float8 AS longitude,
          "storeId", "userId", "deliverymanId"
`

type CreateOrderParams struct {
	Note        string      `json:"note"`
	Address     string      `json:"address"`
	Status      int16       `json:"status"`
	Products    []byte      `json:"products"`
	DeliveryFee float64     `json:"deliveryFee"`
	Total       float64     `json:"total"`
	Payment     int32       `json:"payment"`
	Point       float64     `json:"point"`
	Point_2     float64     `json:"point_2"`
	OrderedAt   pgtype.Date `json:"orderedAt"`
	StoreId     int32       `json:"storeId"`
	UserId      int32       `json:"userId"`
}

type CreateOrderRow struct {
	ID                       int32              `json:"id"`
	Note                     string             `json:"note"`
	Address                  string             `json:"address"`
	Status                   int16              `json:"status"`
	Products                 []byte             `json:"products"`
	DeliveryFee              float64            `json:"deliveryFee"`
	Total                    float64            `json:"total"`
	Payment                  int32              `json:"payment"`
	ScoreClient              *float64           `json:"scoreClient"`
	ScoreDeliveryman         *float64           `json:"scoreDeliveryman"`
	NotificationsClient      float64            `json:"notificationsClient"`
	NotificationsDeliveryman float64            `json:"notificationsDeliveryman"`
	OrderedAt                pgtype.Date        `json:"orderedAt"`
	CreatedAt                pgtype.Timestamptz `json:"createdAt"`
	Latitude                 float64            `json:"latitude"`
	Longitude                float64            `json:"longitude"`
	StoreId                  int32              `json:"storeId"`
	UserId                   int32              `json:"userId"`
	DeliverymanId            *int32             `json:"deliverymanId"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.Note,
		arg.Address,
		arg.Status,
		arg.Products,
		arg.DeliveryFee,
		arg.Total,
		arg.Payment,
		arg.Point,
		arg.Point_2,
		arg.OrderedAt,
		arg.StoreId,
		arg.UserId,
	)
	var i CreateOrderRow
	err := row.Scan(
		&i.ID,
		&i.Note,
		&i.Address,
		&i.Status,
		&i.Products,
		&i.DeliveryFee,
		&i.Total,
		&i.Payment,
		&i.ScoreClient,
		&i.ScoreDeliveryman,
		&i.NotificationsClient,
		&i.NotificationsDeliveryman,
		&i.OrderedAt,
		&i.CreatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.StoreId,
		&i.UserId,
		&i.DeliverymanId,
	)
	return i, err
}

const getOrderByUser = `-- name: GetOrderByUser :one
SELECT o.id, o.note, o.address, o.status, o.products, o."deliveryFee", o.total,
       o.payment, o."scoreClient", o."scoreDeliveryman",
       o."notificationsClient", o."notificationsDeliveryman",
       o."orderedAt", o."createdAt",
       o.location[0]::float8 AS latitude,
       o.location[1]::float8 AS longitude,
       st.id AS store_id, st.name AS store_name, st.address AS store_address,
       st.location[0]::float8 AS store_latitude,
       st.location[1]::float8 AS store_longitude,
       c.image AS company_image, c.marker AS company_marker,
       u.id AS deliveryman_id, u."fullName" AS deliveryman_full_name, u.image AS deliveryman_image
FROM "order" o
INNER JOIN store st ON st.id = o."storeId"
INNER JOIN company c ON c.id = st."companyId"
LEFT JOIN "user" u ON u.id = o."deliverymanId"
WHERE o.id = $1 AND o."userId" = $2
`

type GetOrderByUserParams struct {
	ID     int32 `json:"id"`
	UserId int32 `json:"userId"`
}

type GetOrderByUserRow struct {
	ID                       int32              `json:"id"`
	Note                     string             `json:"note"`
	Address                  string             `json:"address"`
	Status                   int16              `json:"status"`
	Products                 []byte             `json:"products"`
	DeliveryFee              float64            `json:"deliveryFee"`
	Total                    float64            `json:"total"`
	Payment                  int32              `json:"payment"`
	ScoreClient              *float64           `json:"scoreClient"`
	ScoreDeliveryman         *float64           `json:"scoreDeliveryman"`
	NotificationsClient      float64            `json:"notificationsClient"`
	NotificationsDeliveryman float64            `json:"notificationsDeliveryman"`
	OrderedAt                pgtype.Date        `json:"orderedAt"`
	CreatedAt                pgtype.Timestamptz `json:"createdAt"`
	Latitude                 float64            `json:"latitude"`
	Longitude                float64            `json:"longitude"`
	StoreID                  int32              `json:"store_id"`
	StoreName                string             `json:"store_name"`
	StoreAddress             string             `json:"store_address"`
	StoreLatitude            float64            `json:"store_latitude"`
	StoreLongitude           float64            `json:"store_longitude"`
	CompanyImage             string             `json:"company_image"`
	CompanyMarker            string             `json:"company_marker"`
	DeliverymanID            *int32             `json:"deliveryman_id"`
	DeliverymanFullName      *string            `json:"deliveryman_full_name"`
	DeliverymanImage         *string            `json:"deliveryman_image"`
}

func (q *Queries) GetOrderByUser(ctx context.Context, arg GetOrderByUserParams) (GetOrderByUserRow, error) {
	row := q.db.QueryRow(ctx, getOrderByUser, arg.ID, arg.UserId)
	var i GetOrderByUserRow
	err := row.Scan(
		&i.ID,
		&i.Note,
		&i.Address,
		&i.Status,
		&i.Products,
		&i.DeliveryFee,
		&i.Total,
		&i.Payment,
		&i.ScoreClient,
		&i.ScoreDeliveryman,
		&i.NotificationsClient,
		&i.NotificationsDeliveryman,
		&i.OrderedAt,
		&i.CreatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.StoreID,
		&i.StoreName,
		&i.StoreAddress,
		&i.StoreLatitude,
		&i.StoreLongitude,
		&i.CompanyImage,
		&i.CompanyMarker,
		&i.DeliverymanID,
		&i.DeliverymanFullName,
		&i.DeliverymanImage,
	)
	return i, err
}

const getStoreOwnerIDByOrder = `-- name: GetStoreOwnerIDByOrder :one
SELECT st."userId" AS owner_id
FROM "order" o
INNER JOIN store st ON st.id = o."storeId"
WHERE o.id = $1
`

// Dueno de la tienda del pedido: destino de la notificacion al comercio.
func (q *Queries) GetStoreOwnerIDByOrder(ctx context.Context, id int32) (*int32, error) {
	row := q.db.QueryRow(ctx, getStoreOwnerIDByOrder, id)
	var owner_id *int32
	err := row.Scan(&owner_id)
	return owner_id, err
}

const listCategoriesNearby = `-- name: ListCategoriesNearby :many
SELECT ct.id, ct.name, ct.image,
       ct.location[0]::float8 AS latitude,
       ct.location[1]::float8 AS longitude
FROM vw_category ct
WHERE ST_DistanceSphere(
        ST_MakePoint($1::float8, $2::float8),
        ct.location::geometry
      ) <= $3::float8
ORDER BY ct.id
LIMIT $5::int OFFSET $4::int
`

type ListCategoriesNearbyParams struct {
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
	Km          float64 `json:"km"`
	OffsetCount int32   `json:"offset_count"`
	LimitCount  int32   `json:"limit_count"`
}

type ListCategoriesNearbyRow struct {
	ID        int32   `json:"id"`
	Name      string  `json:"name"`
	Image     string  `json:"image"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

func (q *Queries) ListCategoriesNearby(ctx context.Context, arg ListCategoriesNearbyParams) ([]ListCategoriesNearbyRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesNearby,
		arg.Latitude,
		arg.Longitude,
		arg.Km,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesNearbyRow{}
	for rows.Next() {
		var i ListCategoriesNearbyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompaniesNearby = `-- name: ListCompaniesNearby :many

SELECT DISTINCT ON (st.id)
    st.id, st."storeId", st.name, st.address, st.contact, st.image,
    st."categoryId", st.open, st.close, st.day, st."isOpen",
    st.location[0]::float8 AS latitude,
    st.location[1]::float8 AS longitude
FROM vw_company st
WHERE ST_DistanceSphere(
        ST_MakePoint($1::float8, $2::float8),
        st.location::geometry
      ) <= $3::float8
  AND ($4::int <= 0 OR st."categoryId" = $4::int)
ORDER BY st.id
LIMIT $6::int OFFSET $5::int
`

type ListCompaniesNearbyParams struct {
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
	Km          float64 `json:"km"`
	Categoryid  int32   `json:"categoryid"`
	OffsetCount int32   `json:"offset_count"`
	LimitCount  int32   `json:"limit_count"`
}

type ListCompaniesNearbyRow struct {
	ID         int32       `json:"id"`
	StoreId    int32       `json:"storeId"`
	Name       string      `json:"name"`
	Address    string      `json:"address"`
	Contact    string      `json:"contact"`
	Image      string      `json:"image"`
	CategoryId int32       `json:"categoryId"`
	Open       pgtype.Time `json:"open"`
	Close      pgtype.Time `json:"close"`
	Day        int16       `json:"day"`
	IsOpen     *bool       `json:"isOpen"`
	Latitude   float64     `json:"latitude"`
	Longitude  float64     `json:"longitude"`
}

// Consultas del mercado (client/market). Las columnas point se exponen como
// latitud/longitud y la API arma {"x": lat, "y": lng}, igual que hacia
// node-postgres en la version NestJS.
//
// El filtro de cercania replica FilterKM.STORES_NEARBY = 80000000 (en la
// practica, sin limite: todas las tiendas). Se usa ST_MakePoint en lugar de
// ST_GeomFromText para que los parametros sean float8 tipados.
func (q *Queries) ListCompaniesNearby(ctx context.Context, arg ListCompaniesNearbyParams) ([]ListCompaniesNearbyRow, error) {
	rows, err := q.db.Query(ctx, listCompaniesNearby,
		arg.Latitude,
		arg.Longitude,
		arg.Km,
		arg.Categoryid,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompaniesNearbyRow{}
	for rows.Next() {
		var i ListCompaniesNearbyRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreId,
			&i.Name,
			&i.Address,
			&i.Contact,
			&i.Image,
			&i.CategoryId,
			&i.Open,
			&i.Close,
			&i.Day,
			&i.IsOpen,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryFees = `-- name: ListDeliveryFees :many
SELECT s.name,
       s."companyId",
       c.image,
       c.marker,
       s.id AS store_id,
       (s."startupCost" + (
           (ST_DistanceSphere(
               ST_MakePoint($1::float8, $2::float8),
               s.location::geometry
           ) / 1000) * s."costKm"
       ))::float8 AS deliveryfee
FROM store s
INNER JOIN company c ON c.id = s."companyId"
WHERE s.id = ANY($3::int[])
`

type ListDeliveryFeesParams struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	StoreIds  []int32 `json:"store_ids"`
}

type ListDeliveryFeesRow struct {
	Name        string  `json:"name"`
	CompanyId   *int32  `json:"companyId"`
	Image       string  `json:"image"`
	Marker      string  `json:"marker"`
	StoreID     int32   `json:"store_id"`
	Deliveryfee float64 `json:"deliveryfee"`
}

// El alias va sin comillas a proposito: PostgreSQL lo devuelve en minusculas
// ("deliveryfee"), que es la clave que espera el cliente.
func (q *Queries) ListDeliveryFees(ctx context.Context, arg ListDeliveryFeesParams) ([]ListDeliveryFeesRow, error) {
	rows, err := q.db.Query(ctx, listDeliveryFees, arg.Latitude, arg.Longitude, arg.StoreIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeliveryFeesRow{}
	for rows.Next() {
		var i ListDeliveryFeesRow
		if err := rows.Scan(
			&i.Name,
			&i.CompanyId,
			&i.Image,
			&i.Marker,
			&i.StoreID,
			&i.Deliveryfee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNearbyStoreIDs = `-- name: ListNearbyStoreIDs :many
SELECT DISTINCT st."storeId"
FROM vw_company st
WHERE ST_DistanceSphere(
        ST_MakePoint($1::float8, $2::float8),
        st.location::geometry
      ) <= $3::float8
  AND st.id = ANY($4::int[])
  AND st."isOpen" = true
`

type ListNearbyStoreIDsParams struct {
	Latitude   float64 `json:"latitude"`
	Longitude  float64 `json:"longitude"`
	Km         float64 `json:"km"`
	CompanyIds []int32 `json:"company_ids"`
}

// Tiendas abiertas y cercanas de una lista de companias (paso previo al costo
// de envio). Reproduce MarketService.deliveryCost.
func (q *Queries) ListNearbyStoreIDs(ctx context.Context, arg ListNearbyStoreIDsParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, listNearbyStoreIDs,
		arg.Latitude,
		arg.Longitude,
		arg.Km,
		arg.CompanyIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var storeId int32
		if err := rows.Scan(&storeId); err != nil {
			return nil, err
		}
		items = append(items, storeId)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT o.id, o.note, o.address, o.status, o.products, o."deliveryFee", o.total,
       o.payment, o."scoreClient", o."scoreDeliveryman",
       o."notificationsClient", o."notificationsDeliveryman",
       o."orderedAt", o."createdAt",
       o.location[0]::float8 AS latitude,
       o.location[1]::float8 AS longitude,
       st.id AS store_id, st.name AS store_name, st.address AS store_address,
       st.location[0]::float8 AS store_latitude,
       st.location[1]::float8 AS store_longitude,
       c.image AS company_image, c.marker AS company_marker,
       u.id AS deliveryman_id, u."fullName" AS deliveryman_full_name, u.image AS deliveryman_image
FROM "order" o
INNER JOIN store st ON st.id = o."storeId"
INNER JOIN company c ON c.id = st."companyId"
LEFT JOIN "user" u ON u.id = o."deliverymanId"
WHERE o."userId" = $1::int
  AND (o.status <= $2::smallint OR o.status = $3::smallint)
ORDER BY o.id DESC
`

type ListOrdersByUserParams struct {
	UserID          int32 `json:"user_id"`
	StatusDelivered int16 `json:"status_delivered"`
	StatusCancelled int16 `json:"status_cancelled"`
}

type ListOrdersByUserRow struct {
	ID                       int32              `json:"id"`
	Note                     string             `json:"note"`
	Address                  string             `json:"address"`
	Status                   int16              `json:"status"`
	Products                 []byte             `json:"products"`
	DeliveryFee              float64            `json:"deliveryFee"`
	Total                    float64            `json:"total"`
	Payment                  int32              `json:"payment"`
	ScoreClient              *float64           `json:"scoreClient"`
	ScoreDeliveryman         *float64           `json:"scoreDeliveryman"`
	NotificationsClient      float64            `json:"notificationsClient"`
	NotificationsDeliveryman float64            `json:"notificationsDeliveryman"`
	OrderedAt                pgtype.Date        `json:"orderedAt"`
	CreatedAt                pgtype.Timestamptz `json:"createdAt"`
	Latitude                 float64            `json:"latitude"`
	Longitude                float64            `json:"longitude"`
	StoreID                  int32              `json:"store_id"`
	StoreName                string             `json:"store_name"`
	StoreAddress             string             `json:"store_address"`
	StoreLatitude            float64            `json:"store_latitude"`
	StoreLongitude           float64            `json:"store_longitude"`
	CompanyImage             string             `json:"company_image"`
	CompanyMarker            string             `json:"company_marker"`
	DeliverymanID            *int32             `json:"deliveryman_id"`
	DeliverymanFullName      *string            `json:"deliveryman_full_name"`
	DeliverymanImage         *string            `json:"deliveryman_image"`
}

// Pedidos del cliente: status <= DELIVERED o CANCELLED, con las relaciones que
// proyecta la consulta original de MarketService.findOrders.
func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]ListOrdersByUserRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.StatusDelivered, arg.StatusCancelled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersByUserRow{}
	for rows.Next() {
		var i ListOrdersByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Note,
			&i.Address,
			&i.Status,
			&i.Products,
			&i.DeliveryFee,
			&i.Total,
			&i.Payment,
			&i.ScoreClient,
			&i.ScoreDeliveryman,
			&i.NotificationsClient,
			&i.NotificationsDeliveryman,
			&i.OrderedAt,
			&i.CreatedAt,
			&i.Latitude,
			&i.Longitude,
			&i.StoreID,
			&i.StoreName,
			&i.StoreAddress,
			&i.StoreLatitude,
			&i.StoreLongitude,
			&i.CompanyImage,
			&i.CompanyMarker,
			&i.DeliverymanID,
			&i.DeliverymanFullName,
			&i.DeliverymanImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCompany = `-- name: ListProductsByCompany :many
SELECT id, "companyId", "companyName", name, image, description, type, price
FROM vw_product
WHERE "companyId" = $1
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListProductsByCompanyParams struct {
	CompanyId *int32 `json:"companyId"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListProductsByCompany(ctx context.Context, arg ListProductsByCompanyParams) ([]VwProduct, error) {
	rows, err := q.db.Query(ctx, listProductsByCompany, arg.CompanyId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwProduct{}
	for rows.Next() {
		var i VwProduct
		if err := rows.Scan(
			&i.ID,
			&i.CompanyId,
			&i.CompanyName,
			&i.Name,
			&i.Image,
			&i.Description,
			&i.Type,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCompanyIDs = `-- name: ListProductsByCompanyIDs :many
SELECT id, "companyId", "companyName", name, image, description, type, price
FROM vw_product
WHERE "companyId" = ANY($1::int[])
ORDER BY "companyId"
`

func (q *Queries) ListProductsByCompanyIDs(ctx context.Context, companyIds []int32) ([]VwProduct, error) {
	rows, err := q.db.Query(ctx, listProductsByCompanyIDs, companyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwProduct{}
	for rows.Next() {
		var i VwProduct
		if err := rows.Scan(
			&i.ID,
			&i.CompanyId,
			&i.CompanyName,
			&i.Name,
			&i.Image,
			&i.Description,
			&i.Type,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const qualifyOrder = `-- name: QualifyOrder :execrows
UPDATE "order"
SET status = $1::smallint, "scoreClient" = $2::float8
WHERE id = $3::int AND "userId" = $4::int
`

type QualifyOrderParams struct {
	StatusQualified int16   `json:"status_qualified"`
	ScoreClient     float64 `json:"score_client"`
	OrderID         int32   `json:"order_id"`
	UserID          int32   `json:"user_id"`
}

func (q *Queries) QualifyOrder(ctx context.Context, arg QualifyOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, qualifyOrder,
		arg.StatusQualified,
		arg.ScoreClient,
		arg.OrderID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
