// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID        int32              `json:"id"`
	Alias     string             `json:"alias"`
	Address   string             `json:"address"`
	Location  pgtype.Point       `json:"location"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt pgtype.Timestamp   `json:"deletedAt"`
	UserId    *int32             `json:"userId"`
}

type Balance struct {
	UserId int32 `json:"userId"`
	// Balance of money the deliveryman has to be able to take orders
	Balance float64 `json:"balance"`
	// Percentage of the value of the shipment. Benefit for the deliveryman
	Profit float64 `json:"profit"`
	// Amount to be returned to the deliveryman. This value increases when the deliveryman takes orders with electronic payments
	Amount float64 `json:"amount"`
	// Money that the client has to make payments in the APP.
	Money     float64            `json:"money"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Category struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Image     string             `json:"image"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Chat struct {
	ID        int32              `json:"id"`
	Message   string             `json:"message"`
	Type      int16              `json:"type"`
	Status    int16              `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	FromId    int32              `json:"fromId"`
	ToId      *int32             `json:"toId"`
	OrderId   int32              `json:"orderId"`
}

type Company struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Address   string             `json:"address"`
	Contact   string             `json:"contact"`
	Image     string             `json:"image"`
	Marker    string             `json:"marker"`
	Email     string             `json:"email"`
	Location  pgtype.Point       `json:"location"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	UserId    *int32             `json:"userId"`
}

type CompanyCategory struct {
	ID         int32              `json:"id"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
	CompanyId  int32              `json:"companyId"`
	CategoryId int32              `json:"categoryId"`
}

type Credit struct {
	ID int32 `json:"id"`
	// Amount that the delivery person charged to your balance sheet
	Amount        float64            `json:"amount"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	DeliverymanId *int32             `json:"deliverymanId"`
}

type HoursOperation struct {
	ID       int32       `json:"id"`
	Day      int16       `json:"day"`
	Open     pgtype.Time `json:"open"`
	Close    pgtype.Time `json:"close"`
	TimeZone int16       `json:"timeZone"`
	StoreId  *int32      `json:"storeId"`
}

type Order struct {
	ID               int32    `json:"id"`
	Note             string   `json:"note"`
	Address          string   `json:"address"`
	Status           int16    `json:"status"`
	ScoreDeliveryman *float64 `json:"scoreDeliveryman"`
	ScoreClient      *float64 `json:"scoreClient"`
	Products         []byte   `json:"products"`
	DeliveryFee      float64  `json:"deliveryFee"`
	Total            float64  `json:"total"`
	// Profit the deliveryman by the shipment
	DeliverymanProfit *float64 `json:"deliverymanProfit"`
	// Profit the app by the shipment
	DeliveryAppProfit *float64 `json:"deliveryAppProfit"`
	// Types Payment
	Payment                  int32              `json:"payment"`
	Location                 pgtype.Point       `json:"location"`
	NotificationsDeliveryman float64            `json:"notificationsDeliveryman"`
	NotificationsClient      float64            `json:"notificationsClient"`
	OrderedAt                pgtype.Date        `json:"orderedAt"`
	CreatedAt                pgtype.Timestamptz `json:"createdAt"`
	StoreId                  int32              `json:"storeId"`
	UserId                   int32              `json:"userId"`
	DeliverymanId            *int32             `json:"deliverymanId"`
}

type Payment struct {
	ID        int32              `json:"id"`
	Money     float64            `json:"money"`
	Status    int16              `json:"status"`
	Currency  string             `json:"currency"`
	Products  []byte             `json:"products"`
	Response  []byte             `json:"response"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	UserId    *int32             `json:"userId"`
}

type Product struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Image       string             `json:"image"`
	Type        int32              `json:"type"`
	Price       float64            `json:"price"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt   pgtype.Timestamp   `json:"deletedAt"`
	CompanyId   *int32             `json:"companyId"`
}

type Session struct {
	ID        int32   `json:"id"`
	IdDevice  string  `json:"idDevice"`
	TokenPush *string `json:"tokenPush"`
	// If true. The deliveryman wants to receive orders
	IsOnline  bool               `json:"isOnline"`
	Location  pgtype.Point       `json:"location"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdateAt  pgtype.Timestamptz `json:"updateAt"`
	UserId    int32              `json:"userId"`
}

type Store struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Address     string             `json:"address"`
	Contact     string             `json:"contact"`
	Email       string             `json:"email"`
	StartupCost float64            `json:"startupCost"`
	CostKm      float64            `json:"costKm"`
	Location    pgtype.Point       `json:"location"`
	Sales       int32              `json:"sales"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt   pgtype.Timestamp   `json:"deletedAt"`
	CompanyId   *int32             `json:"companyId"`
	UserId      *int32             `json:"userId"`
}

type User struct {
	ID                int32              `json:"id"`
	IdGoogle          *string            `json:"idGoogle"`
	FullName          string             `json:"fullName"`
	Email             string             `json:"email"`
	Phone             *string            `json:"phone"`
	Password          string             `json:"password"`
	PasswordTemporary *string            `json:"passwordTemporary"`
	Image             string             `json:"image"`
	IsActive          bool               `json:"isActive"`
	Roles             []string           `json:"roles"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
}

type VwCategory struct {
	ID       int32        `json:"id"`
	Name     string       `json:"name"`
	Image    string       `json:"image"`
	Location pgtype.Point `json:"location"`
}

type VwCompany struct {
	ID         int32        `json:"id"`
	StoreId    int32        `json:"storeId"`
	Name       string       `json:"name"`
	Address    string       `json:"address"`
	Contact    string       `json:"contact"`
	Image      string       `json:"image"`
	Location   pgtype.Point `json:"location"`
	CategoryId int32        `json:"categoryId"`
	Open       pgtype.Time  `json:"open"`
	Close      pgtype.Time  `json:"close"`
	Day        int16        `json:"day"`
	IsOpen     *bool        `json:"isOpen"`
}

type VwProduct struct {
	ID          int32   `json:"id"`
	CompanyId   *int32  `json:"companyId"`
	CompanyName string  `json:"companyName"`
	Name        string  `json:"name"`
	Image       string  `json:"image"`
	Description string  `json:"description"`
	Type        int32   `json:"type"`
	Price       float64 `json:"price"`
}
