// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package store

import (
	"context"
)

const addBalanceMoney = `-- name: AddBalanceMoney :exec
INSERT INTO balance ("userId", money)
VALUES ($1, $2)
ON CONFLICT ("userId") DO UPDATE
SET money = balance.money + EXCLUDED.money, "updatedAt" = now()
`

type AddBalanceMoneyParams struct {
	UserId int32   `json:"userId"`
	Money  float64 `json:"money"`
}

// Suma dinero al saldo del cliente, creando el registro si no existe.
func (q *Queries) AddBalanceMoney(ctx context.Context, arg AddBalanceMoneyParams) error {
	_, err := q.db.Exec(ctx, addBalanceMoney, arg.UserId, arg.Money)
	return err
}

const createPayment = `-- name: CreatePayment :one

INSERT INTO payment (money, status, currency, products, response, "userId")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, money, status, currency, products, response, "createdAt", "updatedAt", "userId"
`

type CreatePaymentParams struct {
	Money    float64 `json:"money"`
	Status   int16   `json:"status"`
	Currency string  `json:"currency"`
	Products []byte  `json:"products"`
	Response []byte  `json:"response"`
	UserId   *int32  `json:"userId"`
}

// Pagos con tarjeta. El campo response guarda la respuesta cruda de la pasarela
// (Stripe), igual que la version NestJS.
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.Money,
		arg.Status,
		arg.Currency,
		arg.Products,
		arg.Response,
		arg.UserId,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Money,
		&i.Status,
		&i.Currency,
		&i.Products,
		&i.Response,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserId,
	)
	return i, err
}

const getPaymentByIDAndUser = `-- name: GetPaymentByIDAndUser :one
SELECT id, money, status, currency, products, response, "createdAt", "updatedAt", "userId"
FROM payment
WHERE id = $1 AND "userId" = $2
`

type GetPaymentByIDAndUserParams struct {
	ID     int32  `json:"id"`
	UserId *int32 `json:"userId"`
}

func (q *Queries) GetPaymentByIDAndUser(ctx context.Context, arg GetPaymentByIDAndUserParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIDAndUser, arg.ID, arg.UserId)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Money,
		&i.Status,
		&i.Currency,
		&i.Products,
		&i.Response,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserId,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :execrows
UPDATE payment
SET status = $1::smallint, "updatedAt" = now()
WHERE id = $2::int AND status = $3::smallint
`

type UpdatePaymentStatusParams struct {
	NewStatus     int16 `json:"new_status"`
	PaymentID     int32 `json:"payment_id"`
	CurrentStatus int16 `json:"current_status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePaymentStatus, arg.NewStatus, arg.PaymentID, arg.CurrentStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
