// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: petition.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyOrder = `-- name: ApplyOrder :execrows
UPDATE "order"
SET "deliverymanId" = $1::int,
    status = $2::smallint,
    "deliverymanProfit" = $3::float8,
    "deliveryAppProfit" = $4::float8
WHERE id = $5::int
  AND status = $6::smallint
  AND "deliverymanId" IS NULL
`

type ApplyOrderParams struct {
	DeliverymanID     int32   `json:"deliveryman_id"`
	NewStatus         int16   `json:"new_status"`
	DeliverymanProfit float64 `json:"deliveryman_profit"`
	DeliveryAppProfit float64 `json:"delivery_app_profit"`
	OrderID           int32   `json:"order_id"`
	CurrentStatus     int16   `json:"current_status"`
}

func (q *Queries) ApplyOrder(ctx context.Context, arg ApplyOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyOrder,
		arg.DeliverymanID,
		arg.NewStatus,
		arg.DeliverymanProfit,
		arg.DeliveryAppProfit,
		arg.OrderID,
		arg.CurrentStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelOrder = `-- name: CancelOrder :execrows
UPDATE "order"
SET status = $1::smallint
WHERE id = $2::int
  AND status = $3::smallint
  AND "deliverymanId" = $4::int
`

type CancelOrderParams struct {
	NewStatus     int16 `json:"new_status"`
	OrderID       int32 `json:"order_id"`
	CurrentStatus int16 `json:"current_status"`
	DeliverymanID int32 `json:"deliveryman_id"`
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelOrder,
		arg.NewStatus,
		arg.OrderID,
		arg.CurrentStatus,
		arg.DeliverymanID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const collectOrder = `-- name: CollectOrder :execrows
UPDATE "order"
SET status = $1::smallint
WHERE id = $2::int
  AND status = $3::smallint
  AND "deliverymanId" = $4::int
`

type CollectOrderParams struct {
	NewStatus     int16 `json:"new_status"`
	OrderID       int32 `json:"order_id"`
	CurrentStatus int16 `json:"current_status"`
	DeliverymanID int32 `json:"deliveryman_id"`
}

func (q *Queries) CollectOrder(ctx context.Context, arg CollectOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, collectOrder,
		arg.NewStatus,
		arg.OrderID,
		arg.CurrentStatus,
		arg.DeliverymanID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deliverOrder = `-- name: DeliverOrder :execrows
UPDATE "order"
SET status = $1::smallint,
    "scoreDeliveryman" = $2::float8
WHERE id = $3::int
  AND status = $4::smallint
  AND "deliverymanId" = $5::int
`

type DeliverOrderParams struct {
	NewStatus        int16   `json:"new_status"`
	ScoreDeliveryman float64 `json:"score_deliveryman"`
	OrderID          int32   `json:"order_id"`
	CurrentStatus    int16   `json:"current_status"`
	DeliverymanID    int32   `json:"deliveryman_id"`
}

func (q *Queries) DeliverOrder(ctx context.Context, arg DeliverOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deliverOrder,
		arg.NewStatus,
		arg.ScoreDeliveryman,
		arg.OrderID,
		arg.CurrentStatus,
		arg.DeliverymanID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrderForApply = `-- name: GetOrderForApply :one
SELECT "deliveryFee", payment
FROM "order"
WHERE id = $1
`

type GetOrderForApplyRow struct {
	DeliveryFee float64 `json:"deliveryFee"`
	Payment     int32   `json:"payment"`
}

func (q *Queries) GetOrderForApply(ctx context.Context, id int32) (GetOrderForApplyRow, error) {
	row := q.db.QueryRow(ctx, getOrderForApply, id)
	var i GetOrderForApplyRow
	err := row.Scan(&i.DeliveryFee, &i.Payment)
	return i, err
}

const getOrderForCancel = `-- name: GetOrderForCancel :one
SELECT o.total, o."deliverymanProfit", o."deliveryAppProfit", o.payment, o."userId"
FROM "order" o
WHERE o.id = $1 AND o.status = $2
`

type GetOrderForCancelParams struct {
	ID     int32 `json:"id"`
	Status int16 `json:"status"`
}

type GetOrderForCancelRow struct {
	Total             float64  `json:"total"`
	DeliverymanProfit *float64 `json:"deliverymanProfit"`
	DeliveryAppProfit *float64 `json:"deliveryAppProfit"`
	Payment           int32    `json:"payment"`
	UserId            int32    `json:"userId"`
}

func (q *Queries) GetOrderForCancel(ctx context.Context, arg GetOrderForCancelParams) (GetOrderForCancelRow, error) {
	row := q.db.QueryRow(ctx, getOrderForCancel, arg.ID, arg.Status)
	var i GetOrderForCancelRow
	err := row.Scan(
		&i.Total,
		&i.DeliverymanProfit,
		&i.DeliveryAppProfit,
		&i.Payment,
		&i.UserId,
	)
	return i, err
}

const getPetition = `-- name: GetPetition :one
SELECT o.id, o.note, o.address, o.status, o.products, o."deliveryFee", o.total,
       o.payment, o."notificationsDeliveryman", o."notificationsClient",
       o."deliverymanProfit", o."deliveryAppProfit", o."orderedAt", o."createdAt",
       o.location[0]::float8 AS latitude,
       o.location[1]::float8 AS longitude,
       u.id AS user_id, u."fullName" AS user_full_name, u.phone AS user_phone,
       u.image AS user_image,
       st.id AS store_id, st.name AS store_name, st.address AS store_address,
       st.contact AS store_contact,
       st.location[0]::float8 AS store_latitude,
       st.location[1]::float8 AS store_longitude,
       c.image AS company_image
FROM "order" o
INNER JOIN "user" u ON u.id = o."userId"
INNER JOIN store st ON st.id = o."storeId"
INNER JOIN company c ON c.id = st."companyId"
WHERE o.id = $1 AND o."deliverymanId" = $2
`

type GetPetitionParams struct {
	ID            int32  `json:"id"`
	DeliverymanId *int32 `json:"deliverymanId"`
}

type GetPetitionRow struct {
	ID                       int32              `json:"id"`
	Note                     string             `json:"note"`
	Address                  string             `json:"address"`
	Status                   int16              `json:"status"`
	Products                 []byte             `json:"products"`
	DeliveryFee              float64            `json:"deliveryFee"`
	Total                    float64            `json:"total"`
	Payment                  int32              `json:"payment"`
	NotificationsDeliveryman float64            `json:"notificationsDeliveryman"`
	NotificationsClient      float64            `json:"notificationsClient"`
	DeliverymanProfit        *float64           `json:"deliverymanProfit"`
	DeliveryAppProfit        *float64           `json:"deliveryAppProfit"`
	OrderedAt                pgtype.Date        `json:"orderedAt"`
	CreatedAt                pgtype.Timestamptz `json:"createdAt"`
	Latitude                 float64            `json:"latitude"`
	Longitude                float64            `json:"longitude"`
	UserID                   int32              `json:"user_id"`
	UserFullName             string             `json:"user_full_name"`
	UserPhone                *string            `json:"user_phone"`
	UserImage                string             `json:"user_image"`
	StoreID                  int32              `json:"store_id"`
	StoreName                string             `json:"store_name"`
	StoreAddress             string             `json:"store_address"`
	StoreContact             string             `json:"store_contact"`
	StoreLatitude            float64            `json:"store_latitude"`
	StoreLongitude           float64            `json:"store_longitude"`
	CompanyImage             string             `json:"company_image"`
}

func (q *Queries) GetPetition(ctx context.Context, arg GetPetitionParams) (GetPetitionRow, error) {
	row := q.db.QueryRow(ctx, getPetition, arg.ID, arg.DeliverymanId)
	var i GetPetitionRow
	err := row.Scan(
		&i.ID,
		&i.Note,
		&i.Address,
		&i.Status,
		&i.Products,
		&i.DeliveryFee,
		&i.Total,
		&i.Payment,
		&i.NotificationsDeliveryman,
		&i.NotificationsClient,
		&i.DeliverymanProfit,
		&i.DeliveryAppProfit,
		&i.OrderedAt,
		&i.CreatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.UserID,
		&i.UserFullName,
		&i.UserPhone,
		&i.UserImage,
		&i.StoreID,
		&i.StoreName,
		&i.StoreAddress,
		&i.StoreContact,
		&i.StoreLatitude,
		&i.StoreLongitude,
		&i.CompanyImage,
	)
	return i, err
}

const listNearPetitions = `-- name: ListNearPetitions :many

SELECT o.id, o.note, o.address, o.status, o.products, o."deliveryFee", o.total,
       o.payment, o."notificationsDeliveryman", o."notificationsClient",
       o."deliverymanProfit", o."deliveryAppProfit", o."orderedAt", o."createdAt",
       o.location[0]::float8 AS latitude,
       o.location[1]::float8 AS longitude,
       u.id AS user_id, u."fullName" AS user_full_name, u.phone AS user_phone,
       u.image AS user_image,
       st.id AS store_id, st.name AS store_name, st.address AS store_address,
       st.contact AS store_contact,
       st.location[0]::float8 AS store_latitude,
       st.location[1]::float8 AS store_longitude,
       c.image AS company_image
FROM "order" o
INNER JOIN "user" u ON u.id = o."userId"
INNER JOIN store st ON st.id = o."storeId"
INNER JOIN company c ON c.id = st."companyId"
WHERE (
        o."deliverymanId" = $1::int
        AND o.status < $2::smallint
      )
   OR (
        o.status = $3::smallint
        AND ST_DistanceSphere(
              ST_MakePoint($4::float8, $5::float8),
              o.location::geometry
            ) <= $6::float8
      )
ORDER BY o.id ASC
`

type ListNearPetitionsParams struct {
	DeliverymanID   int32   `json:"deliveryman_id"`
	StatusDelivered int16   `json:"status_delivered"`
	StatusStarted   int16   `json:"status_started"`
	Latitude        float64 `json:"latitude"`
	Longitude       float64 `json:"longitude"`
	Km              float64 `json:"km"`
}

type ListNearPetitionsRow struct {
	ID                       int32              `json:"id"`
	Note                     string             `json:"note"`
	Address                  string             `json:"address"`
	Status                   int16              `json:"status"`
	Products                 []byte             `json:"products"`
	DeliveryFee              float64            `json:"deliveryFee"`
	Total                    float64            `json:"total"`
	Payment                  int32              `json:"payment"`
	NotificationsDeliveryman float64            `json:"notificationsDeliveryman"`
	NotificationsClient      float64            `json:"notificationsClient"`
	DeliverymanProfit        *float64           `json:"deliverymanProfit"`
	DeliveryAppProfit        *float64           `json:"deliveryAppProfit"`
	OrderedAt                pgtype.Date        `json:"orderedAt"`
	CreatedAt                pgtype.Timestamptz `json:"createdAt"`
	Latitude                 float64            `json:"latitude"`
	Longitude                float64            `json:"longitude"`
	UserID                   int32              `json:"user_id"`
	UserFullName             string             `json:"user_full_name"`
	UserPhone                *string            `json:"user_phone"`
	UserImage                string             `json:"user_image"`
	StoreID                  int32              `json:"store_id"`
	StoreName                string             `json:"store_name"`
	StoreAddress             string             `json:"store_address"`
	StoreContact             string             `json:"store_contact"`
	StoreLatitude            float64            `json:"store_latitude"`
	StoreLongitude           float64            `json:"store_longitude"`
	CompanyImage             string             `json:"company_image"`
}

// Peticiones del repartidor (deliveryman/petition).
// Reproduce PetitionService: cercania con PostGIS, ciclo de vida del pedido y
// ajuste del balance del repartidor.
// Pedidos asignados al repartidor que aun no se entregan, mas los STARTED que
// estan dentro del radio. Mismo filtro que _sqlFilterOrder.
func (q *Queries) ListNearPetitions(ctx context.Context, arg ListNearPetitionsParams) ([]ListNearPetitionsRow, error) {
	rows, err := q.db.Query(ctx, listNearPetitions,
		arg.DeliverymanID,
		arg.StatusDelivered,
		arg.StatusStarted,
		arg.Latitude,
		arg.Longitude,
		arg.Km,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNearPetitionsRow{}
	for rows.Next() {
		var i ListNearPetitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Note,
			&i.Address,
			&i.Status,
			&i.Products,
			&i.DeliveryFee,
			&i.Total,
			&i.Payment,
			&i.NotificationsDeliveryman,
			&i.NotificationsClient,
			&i.DeliverymanProfit,
			&i.DeliveryAppProfit,
			&i.OrderedAt,
			&i.CreatedAt,
			&i.Latitude,
			&i.Longitude,
			&i.UserID,
			&i.UserFullName,
			&i.UserPhone,
			&i.UserImage,
			&i.StoreID,
			&i.StoreName,
			&i.StoreAddress,
			&i.StoreContact,
			&i.StoreLatitude,
			&i.StoreLongitude,
			&i.CompanyImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPetitionHistory = `-- name: ListPetitionHistory :many
SELECT o.id, o.note, o.address, o.status, o.products, o."deliveryFee", o.total,
       o.payment, o."notificationsDeliveryman", o."notificationsClient",
       o."deliverymanProfit", o."deliveryAppProfit", o."orderedAt", o."createdAt",
       o.location[0]::float8 AS latitude,
       o.location[1]::float8 AS longitude,
       u.id AS user_id, u."fullName" AS user_full_name, u.phone AS user_phone,
       u.image AS user_image,
       st.id AS store_id, st.name AS store_name, st.address AS store_address,
       st.contact AS store_contact,
       st.location[0]::float8 AS store_latitude,
       st.location[1]::float8 AS store_longitude,
       c.image AS company_image
FROM "order" o
INNER JOIN "user" u ON u.id = o."userId"
INNER JOIN store st ON st.id = o."storeId"
INNER JOIN company c ON c.id = st."companyId"
WHERE o."deliverymanId" = $1 AND o."orderedAt" = $2
ORDER BY o.id DESC
`

type ListPetitionHistoryParams struct {
	DeliverymanId *int32      `json:"deliverymanId"`
	OrderedAt     pgtype.Date `json:"orderedAt"`
}

type ListPetitionHistoryRow struct {
	ID                       int32              `json:"id"`
	Note                     string             `json:"note"`
	Address                  string             `json:"address"`
	Status                   int16              `json:"status"`
	Products                 []byte             `json:"products"`
	DeliveryFee              float64            `json:"deliveryFee"`
	Total                    float64            `json:"total"`
	Payment                  int32              `json:"payment"`
	NotificationsDeliveryman float64            `json:"notificationsDeliveryman"`
	NotificationsClient      float64            `json:"notificationsClient"`
	DeliverymanProfit        *float64           `json:"deliverymanProfit"`
	DeliveryAppProfit        *float64           `json:"deliveryAppProfit"`
	OrderedAt                pgtype.Date        `json:"orderedAt"`
	CreatedAt                pgtype.Timestamptz `json:"createdAt"`
	Latitude                 float64            `json:"latitude"`
	Longitude                float64            `json:"longitude"`
	UserID                   int32              `json:"user_id"`
	UserFullName             string             `json:"user_full_name"`
	UserPhone                *string            `json:"user_phone"`
	UserImage                string             `json:"user_image"`
	StoreID                  int32              `json:"store_id"`
	StoreName                string             `json:"store_name"`
	StoreAddress             string             `json:"store_address"`
	StoreContact             string             `json:"store_contact"`
	StoreLatitude            float64            `json:"store_latitude"`
	StoreLongitude           float64            `json:"store_longitude"`
	CompanyImage             string             `json:"company_image"`
}

func (q *Queries) ListPetitionHistory(ctx context.Context, arg ListPetitionHistoryParams) ([]ListPetitionHistoryRow, error) {
	rows, err := q.db.Query(ctx, listPetitionHistory, arg.DeliverymanId, arg.OrderedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPetitionHistoryRow{}
	for rows.Next() {
		var i ListPetitionHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Note,
			&i.Address,
			&i.Status,
			&i.Products,
			&i.DeliveryFee,
			&i.Total,
			&i.Payment,
			&i.NotificationsDeliveryman,
			&i.NotificationsClient,
			&i.DeliverymanProfit,
			&i.DeliveryAppProfit,
			&i.OrderedAt,
			&i.CreatedAt,
			&i.Latitude,
			&i.Longitude,
			&i.UserID,
			&i.UserFullName,
			&i.UserPhone,
			&i.UserImage,
			&i.StoreID,
			&i.StoreName,
			&i.StoreAddress,
			&i.StoreContact,
			&i.StoreLatitude,
			&i.StoreLongitude,
			&i.CompanyImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBalanceValues = `-- name: UpdateBalanceValues :execrows
UPDATE balance
SET balance = $1::float8,
    amount = $2::float8,
    money = $3::float8,
    "updatedAt" = now()
WHERE "userId" = $4::int
`

type UpdateBalanceValuesParams struct {
	Balance float64 `json:"balance"`
	Amount  float64 `json:"amount"`
	Money   float64 `json:"money"`
	UserID  int32   `json:"user_id"`
}

// El repartidor ajusta balance/amount y el cliente su money (cancelaciones).
func (q *Queries) UpdateBalanceValues(ctx context.Context, arg UpdateBalanceValuesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBalanceValues,
		arg.Balance,
		arg.Amount,
		arg.Money,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
