// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO product (name, description, image, type, price, "companyId")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, image, type, price, "createdAt", "updatedAt", "companyId"
`

type CreateProductParams struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Image       string  `json:"image"`
	Type        int32   `json:"type"`
	Price       float64 `json:"price"`
	CompanyId   *int32  `json:"companyId"`
}

type CreateProductRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Image       string             `json:"image"`
	Type        int32              `json:"type"`
	Price       float64            `json:"price"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	CompanyId   *int32             `json:"companyId"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Image,
		arg.Type,
		arg.Price,
		arg.CompanyId,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		&i.Type,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyId,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, image, type, price, "createdAt", "updatedAt", "companyId"
FROM product
WHERE id = $1 AND "deletedAt" IS NULL
`

type GetProductByIDRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Image       string             `json:"image"`
	Type        int32              `json:"type"`
	Price       float64            `json:"price"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	CompanyId   *int32             `json:"companyId"`
}

func (q *Queries) GetProductByID(ctx context.Context, id int32) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		&i.Type,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyId,
	)
	return i, err
}

const listProductsByCompanyAdmin = `-- name: ListProductsByCompanyAdmin :many
SELECT id, name, description, image, type, price, "createdAt", "updatedAt", "companyId"
FROM product
WHERE "companyId" = $1 AND "deletedAt" IS NULL
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListProductsByCompanyAdminParams struct {
	CompanyId *int32 `json:"companyId"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type ListProductsByCompanyAdminRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Image       string             `json:"image"`
	Type        int32              `json:"type"`
	Price       float64            `json:"price"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	CompanyId   *int32             `json:"companyId"`
}

func (q *Queries) ListProductsByCompanyAdmin(ctx context.Context, arg ListProductsByCompanyAdminParams) ([]ListProductsByCompanyAdminRow, error) {
	rows, err := q.db.Query(ctx, listProductsByCompanyAdmin, arg.CompanyId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsByCompanyAdminRow{}
	for rows.Next() {
		var i ListProductsByCompanyAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Image,
			&i.Type,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCompanyManager = `-- name: ListProductsByCompanyManager :many

SELECT id, name, description, image, type, price, "createdAt", "updatedAt", "companyId"
FROM product
WHERE "companyId" = $1 AND "deletedAt" IS NULL
ORDER BY id DESC
`

type ListProductsByCompanyManagerRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Image       string             `json:"image"`
	Type        int32              `json:"type"`
	Price       float64            `json:"price"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	CompanyId   *int32             `json:"companyId"`
}

// Productos. Usado por manager/store y por admin/product.
func (q *Queries) ListProductsByCompanyManager(ctx context.Context, companyid *int32) ([]ListProductsByCompanyManagerRow, error) {
	rows, err := q.db.Query(ctx, listProductsByCompanyManager, companyid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsByCompanyManagerRow{}
	for rows.Next() {
		var i ListProductsByCompanyManagerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Image,
			&i.Type,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :execrows
UPDATE product
SET "deletedAt" = now()
WHERE id = $1 AND "deletedAt" IS NULL
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE product
SET name = $2, description = $3, image = $4, type = $5, price = $6, "updatedAt" = now()
WHERE id = $1 AND "deletedAt" IS NULL
RETURNING id, name, description, image, type, price, "createdAt", "updatedAt", "companyId"
`

type UpdateProductParams struct {
	ID          int32   `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Image       string  `json:"image"`
	Type        int32   `json:"type"`
	Price       float64 `json:"price"`
}

type UpdateProductRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Image       string             `json:"image"`
	Type        int32              `json:"type"`
	Price       float64            `json:"price"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	CompanyId   *int32             `json:"companyId"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Image,
		arg.Type,
		arg.Price,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		&i.Type,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyId,
	)
	return i, err
}
