// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: request.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRequest = `-- name: GetRequest :one
SELECT o.id, o.note, o.address, o.status, o.products, o."deliveryFee", o.total,
       o.payment, o."notificationsDeliveryman", o."scoreDeliveryman",
       o."createdAt",
       o.location[0]::float8 AS latitude,
       o.location[1]::float8 AS longitude,
       u.id AS user_id, u."fullName" AS user_full_name, u.phone AS user_phone,
       u.image AS user_image,
       st.id AS store_id, st.name AS store_name, st.address AS store_address,
       st.contact AS store_contact,
       st.location[0]::float8 AS store_latitude,
       st.location[1]::float8 AS store_longitude,
       c.image AS company_image
FROM "order" o
INNER JOIN "user" u ON u.id = o."userId"
INNER JOIN store st ON st.id = o."storeId"
INNER JOIN company c ON c.id = st."companyId"
WHERE o.id = $1
`

type GetRequestRow struct {
	ID                       int32              `json:"id"`
	Note                     string             `json:"note"`
	Address                  string             `json:"address"`
	Status                   int16              `json:"status"`
	Products                 []byte             `json:"products"`
	DeliveryFee              float64            `json:"deliveryFee"`
	Total                    float64            `json:"total"`
	Payment                  int32              `json:"payment"`
	NotificationsDeliveryman float64            `json:"notificationsDeliveryman"`
	ScoreDeliveryman         *float64           `json:"scoreDeliveryman"`
	CreatedAt                pgtype.Timestamptz `json:"createdAt"`
	Latitude                 float64            `json:"latitude"`
	Longitude                float64            `json:"longitude"`
	UserID                   int32              `json:"user_id"`
	UserFullName             string             `json:"user_full_name"`
	UserPhone                *string            `json:"user_phone"`
	UserImage                string             `json:"user_image"`
	StoreID                  int32              `json:"store_id"`
	StoreName                string             `json:"store_name"`
	StoreAddress             string             `json:"store_address"`
	StoreContact             string             `json:"store_contact"`
	StoreLatitude            float64            `json:"store_latitude"`
	StoreLongitude           float64            `json:"store_longitude"`
	CompanyImage             string             `json:"company_image"`
}

func (q *Queries) GetRequest(ctx context.Context, id int32) (GetRequestRow, error) {
	row := q.db.QueryRow(ctx, getRequest, id)
	var i GetRequestRow
	err := row.Scan(
		&i.ID,
		&i.Note,
		&i.Address,
		&i.Status,
		&i.Products,
		&i.DeliveryFee,
		&i.Total,
		&i.Payment,
		&i.NotificationsDeliveryman,
		&i.ScoreDeliveryman,
		&i.CreatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.UserID,
		&i.UserFullName,
		&i.UserPhone,
		&i.UserImage,
		&i.StoreID,
		&i.StoreName,
		&i.StoreAddress,
		&i.StoreContact,
		&i.StoreLatitude,
		&i.StoreLongitude,
		&i.CompanyImage,
	)
	return i, err
}

const listNearRequests = `-- name: ListNearRequests :many

SELECT o.id, o.note, o.address, o.status, o.products, o."deliveryFee", o.total,
       o.payment, o."notificationsDeliveryman", o."scoreDeliveryman",
       o."createdAt",
       o.location[0]::float8 AS latitude,
       o.location[1]::float8 AS longitude,
       u.id AS user_id, u."fullName" AS user_full_name, u.phone AS user_phone,
       u.image AS user_image,
       st.id AS store_id, st.name AS store_name, st.address AS store_address,
       st.contact AS store_contact,
       st.location[0]::float8 AS store_latitude,
       st.location[1]::float8 AS store_longitude,
       c.image AS company_image
FROM "order" o
INNER JOIN "user" u ON u.id = o."userId"
INNER JOIN store st ON st.id = o."storeId"
INNER JOIN company c ON c.id = st."companyId"
WHERE st."userId" = $1 AND o.status < $2
ORDER BY o.id ASC
`

type ListNearRequestsParams struct {
	UserId *int32 `json:"userId"`
	Status int16  `json:"status"`
}

type ListNearRequestsRow struct {
	ID                       int32              `json:"id"`
	Note                     string             `json:"note"`
	Address                  string             `json:"address"`
	Status                   int16              `json:"status"`
	Products                 []byte             `json:"products"`
	DeliveryFee              float64            `json:"deliveryFee"`
	Total                    float64            `json:"total"`
	Payment                  int32              `json:"payment"`
	NotificationsDeliveryman float64            `json:"notificationsDeliveryman"`
	ScoreDeliveryman         *float64           `json:"scoreDeliveryman"`
	CreatedAt                pgtype.Timestamptz `json:"createdAt"`
	Latitude                 float64            `json:"latitude"`
	Longitude                float64            `json:"longitude"`
	UserID                   int32              `json:"user_id"`
	UserFullName             string             `json:"user_full_name"`
	UserPhone                *string            `json:"user_phone"`
	UserImage                string             `json:"user_image"`
	StoreID                  int32              `json:"store_id"`
	StoreName                string             `json:"store_name"`
	StoreAddress             string             `json:"store_address"`
	StoreContact             string             `json:"store_contact"`
	StoreLatitude            float64            `json:"store_latitude"`
	StoreLongitude           float64            `json:"store_longitude"`
	CompanyImage             string             `json:"company_image"`
}

// Peticiones del gerente (manager/request): pedidos entrantes de sus tiendas.
func (q *Queries) ListNearRequests(ctx context.Context, arg ListNearRequestsParams) ([]ListNearRequestsRow, error) {
	rows, err := q.db.Query(ctx, listNearRequests, arg.UserId, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNearRequestsRow{}
	for rows.Next() {
		var i ListNearRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Note,
			&i.Address,
			&i.Status,
			&i.Products,
			&i.DeliveryFee,
			&i.Total,
			&i.Payment,
			&i.NotificationsDeliveryman,
			&i.ScoreDeliveryman,
			&i.CreatedAt,
			&i.Latitude,
			&i.Longitude,
			&i.UserID,
			&i.UserFullName,
			&i.UserPhone,
			&i.UserImage,
			&i.StoreID,
			&i.StoreName,
			&i.StoreAddress,
			&i.StoreContact,
			&i.StoreLatitude,
			&i.StoreLongitude,
			&i.CompanyImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestHistory = `-- name: ListRequestHistory :many
SELECT o.id, o.note, o.address, o.status, o.products, o."deliveryFee", o.total,
       o.payment, o."notificationsDeliveryman", o."scoreDeliveryman",
       o."createdAt",
       o.location[0]::float8 AS latitude,
       o.location[1]::float8 AS longitude,
       u.id AS user_id, u."fullName" AS user_full_name, u.phone AS user_phone,
       u.image AS user_image,
       st.id AS store_id, st.name AS store_name, st.address AS store_address,
       st.contact AS store_contact,
       st.location[0]::float8 AS store_latitude,
       st.location[1]::float8 AS store_longitude,
       c.image AS company_image
FROM "order" o
INNER JOIN "user" u ON u.id = o."userId"
INNER JOIN store st ON st.id = o."storeId"
INNER JOIN company c ON c.id = st."companyId"
WHERE st."userId" = $1 AND o."orderedAt" = $2
ORDER BY o.id DESC
`

type ListRequestHistoryParams struct {
	UserId    *int32      `json:"userId"`
	OrderedAt pgtype.Date `json:"orderedAt"`
}

type ListRequestHistoryRow struct {
	ID                       int32              `json:"id"`
	Note                     string             `json:"note"`
	Address                  string             `json:"address"`
	Status                   int16              `json:"status"`
	Products                 []byte             `json:"products"`
	DeliveryFee              float64            `json:"deliveryFee"`
	Total                    float64            `json:"total"`
	Payment                  int32              `json:"payment"`
	NotificationsDeliveryman float64            `json:"notificationsDeliveryman"`
	ScoreDeliveryman         *float64           `json:"scoreDeliveryman"`
	CreatedAt                pgtype.Timestamptz `json:"createdAt"`
	Latitude                 float64            `json:"latitude"`
	Longitude                float64            `json:"longitude"`
	UserID                   int32              `json:"user_id"`
	UserFullName             string             `json:"user_full_name"`
	UserPhone                *string            `json:"user_phone"`
	UserImage                string             `json:"user_image"`
	StoreID                  int32              `json:"store_id"`
	StoreName                string             `json:"store_name"`
	StoreAddress             string             `json:"store_address"`
	StoreContact             string             `json:"store_contact"`
	StoreLatitude            float64            `json:"store_latitude"`
	StoreLongitude           float64            `json:"store_longitude"`
	CompanyImage             string             `json:"company_image"`
}

func (q *Queries) ListRequestHistory(ctx context.Context, arg ListRequestHistoryParams) ([]ListRequestHistoryRow, error) {
	rows, err := q.db.Query(ctx, listRequestHistory, arg.UserId, arg.OrderedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestHistoryRow{}
	for rows.Next() {
		var i ListRequestHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Note,
			&i.Address,
			&i.Status,
			&i.Products,
			&i.DeliveryFee,
			&i.Total,
			&i.Payment,
			&i.NotificationsDeliveryman,
			&i.ScoreDeliveryman,
			&i.CreatedAt,
			&i.Latitude,
			&i.Longitude,
			&i.UserID,
			&i.UserFullName,
			&i.UserPhone,
			&i.UserImage,
			&i.StoreID,
			&i.StoreName,
			&i.StoreAddress,
			&i.StoreContact,
			&i.StoreLatitude,
			&i.StoreLongitude,
			&i.CompanyImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
