// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO session ("userId", "idDevice", "tokenPush")
VALUES ($1, $2, $3)
RETURNING id, "userId", "idDevice", "tokenPush", "isOnline", "createdAt", "updateAt"
`

type CreateSessionParams struct {
	UserId    int32   `json:"userId"`
	IdDevice  string  `json:"idDevice"`
	TokenPush *string `json:"tokenPush"`
}

type CreateSessionRow struct {
	ID        int32              `json:"id"`
	UserId    int32              `json:"userId"`
	IdDevice  string             `json:"idDevice"`
	TokenPush *string            `json:"tokenPush"`
	IsOnline  bool               `json:"isOnline"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdateAt  pgtype.Timestamptz `json:"updateAt"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserId, arg.IdDevice, arg.TokenPush)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.IdDevice,
		&i.TokenPush,
		&i.IsOnline,
		&i.CreatedAt,
		&i.UpdateAt,
	)
	return i, err
}

const deleteSessionByUserAndDevice = `-- name: DeleteSessionByUserAndDevice :exec
DELETE FROM session
WHERE "userId" = $1 AND "idDevice" = $2
`

type DeleteSessionByUserAndDeviceParams struct {
	UserId   int32  `json:"userId"`
	IdDevice string `json:"idDevice"`
}

func (q *Queries) DeleteSessionByUserAndDevice(ctx context.Context, arg DeleteSessionByUserAndDeviceParams) error {
	_, err := q.db.Exec(ctx, deleteSessionByUserAndDevice, arg.UserId, arg.IdDevice)
	return err
}

const deleteSessionsByTokenPush = `-- name: DeleteSessionsByTokenPush :exec

DELETE FROM session
WHERE "tokenPush" = $1 AND "tokenPush" IS NOT NULL
`

// Sesiones por dispositivo. La columna location es point y se expone como
// latitud/longitud para que la API arme {"x": lat, "y": lng}.
func (q *Queries) DeleteSessionsByTokenPush(ctx context.Context, tokenpush *string) error {
	_, err := q.db.Exec(ctx, deleteSessionsByTokenPush, tokenpush)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, "userId", "idDevice", "tokenPush", "isOnline", "createdAt", "updateAt",
       COALESCE(location[0], 0)::float8 AS latitude,
       COALESCE(location[1], 0)::float8 AS longitude
FROM session
WHERE id = $1
`

type GetSessionByIDRow struct {
	ID        int32              `json:"id"`
	UserId    int32              `json:"userId"`
	IdDevice  string             `json:"idDevice"`
	TokenPush *string            `json:"tokenPush"`
	IsOnline  bool               `json:"isOnline"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdateAt  pgtype.Timestamptz `json:"updateAt"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
}

func (q *Queries) GetSessionByID(ctx context.Context, id int32) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.IdDevice,
		&i.TokenPush,
		&i.IsOnline,
		&i.CreatedAt,
		&i.UpdateAt,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getSessionByUserAndDevice = `-- name: GetSessionByUserAndDevice :one
SELECT id, "userId", "idDevice", "tokenPush", "isOnline", "createdAt", "updateAt",
       COALESCE(location[0], 0)::float8 AS latitude,
       COALESCE(location[1], 0)::float8 AS longitude
FROM session
WHERE "userId" = $1 AND "idDevice" = $2
`

type GetSessionByUserAndDeviceParams struct {
	UserId   int32  `json:"userId"`
	IdDevice string `json:"idDevice"`
}

type GetSessionByUserAndDeviceRow struct {
	ID        int32              `json:"id"`
	UserId    int32              `json:"userId"`
	IdDevice  string             `json:"idDevice"`
	TokenPush *string            `json:"tokenPush"`
	IsOnline  bool               `json:"isOnline"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdateAt  pgtype.Timestamptz `json:"updateAt"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
}

func (q *Queries) GetSessionByUserAndDevice(ctx context.Context, arg GetSessionByUserAndDeviceParams) (GetSessionByUserAndDeviceRow, error) {
	row := q.db.QueryRow(ctx, getSessionByUserAndDevice, arg.UserId, arg.IdDevice)
	var i GetSessionByUserAndDeviceRow
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.IdDevice,
		&i.TokenPush,
		&i.IsOnline,
		&i.CreatedAt,
		&i.UpdateAt,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const listPushTokensByUser = `-- name: ListPushTokensByUser :many
SELECT "tokenPush"
FROM session
WHERE "userId" = $1 AND "tokenPush" IS NOT NULL AND "tokenPush" <> ''
`

func (q *Queries) ListPushTokensByUser(ctx context.Context, userid int32) ([]*string, error) {
	rows, err := q.db.Query(ctx, listPushTokensByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var tokenPush *string
		if err := rows.Scan(&tokenPush); err != nil {
			return nil, err
		}
		items = append(items, tokenPush)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushTokensNearby = `-- name: ListPushTokensNearby :many
SELECT s."tokenPush"
FROM session s
WHERE s."isOnline" = true
  AND s.location IS NOT NULL
  AND s."tokenPush" IS NOT NULL AND s."tokenPush" <> ''
  AND ST_DistanceSphere(ST_GeomFromText('POINT(' || $1::text || ' ' || $2::text || ')'), s.location::geometry) <= $3::float8
`

type ListPushTokensNearbyParams struct {
	Latitude  string  `json:"latitude"`
	Longitude string  `json:"longitude"`
	Km        float64 `json:"km"`
}

// Repartidores en linea dentro del radio (usado por las notificaciones).
func (q *Queries) ListPushTokensNearby(ctx context.Context, arg ListPushTokensNearbyParams) ([]*string, error) {
	rows, err := q.db.Query(ctx, listPushTokensNearby, arg.Latitude, arg.Longitude, arg.Km)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var tokenPush *string
		if err := rows.Scan(&tokenPush); err != nil {
			return nil, err
		}
		items = append(items, tokenPush)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsDetailByID = `-- name: ListSessionsDetailByID :many
SELECT id, "userId", "idDevice", "tokenPush", "isOnline", "createdAt", "updateAt",
       COALESCE(location[0], 0)::float8 AS latitude,
       COALESCE(location[1], 0)::float8 AS longitude
FROM session
WHERE "userId" = $1
ORDER BY id
`

type ListSessionsDetailByIDRow struct {
	ID        int32              `json:"id"`
	UserId    int32              `json:"userId"`
	IdDevice  string             `json:"idDevice"`
	TokenPush *string            `json:"tokenPush"`
	IsOnline  bool               `json:"isOnline"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdateAt  pgtype.Timestamptz `json:"updateAt"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
}

func (q *Queries) ListSessionsDetailByID(ctx context.Context, userid int32) ([]ListSessionsDetailByIDRow, error) {
	rows, err := q.db.Query(ctx, listSessionsDetailByID, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsDetailByIDRow{}
	for rows.Next() {
		var i ListSessionsDetailByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.IdDevice,
			&i.TokenPush,
			&i.IsOnline,
			&i.CreatedAt,
			&i.UpdateAt,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionExistsByUserAndDevice = `-- name: SessionExistsByUserAndDevice :one
SELECT EXISTS (
    SELECT 1 FROM session WHERE "userId" = $1 AND "idDevice" = $2
) AS exists
`

type SessionExistsByUserAndDeviceParams struct {
	UserId   int32  `json:"userId"`
	IdDevice string `json:"idDevice"`
}

// Comprobacion ligera usada por el middleware de autenticacion.
func (q *Queries) SessionExistsByUserAndDevice(ctx context.Context, arg SessionExistsByUserAndDeviceParams) (bool, error) {
	row := q.db.QueryRow(ctx, sessionExistsByUserAndDevice, arg.UserId, arg.IdDevice)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSessionActivate = `-- name: UpdateSessionActivate :execrows
UPDATE session
SET "isOnline" = $3, location = point($4, $5), "updateAt" = now()
WHERE "userId" = $1 AND "idDevice" = $2
`

type UpdateSessionActivateParams struct {
	UserId   int32   `json:"userId"`
	IdDevice string  `json:"idDevice"`
	IsOnline bool    `json:"isOnline"`
	Point    float64 `json:"point"`
	Point_2  float64 `json:"point_2"`
}

func (q *Queries) UpdateSessionActivate(ctx context.Context, arg UpdateSessionActivateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSessionActivate,
		arg.UserId,
		arg.IdDevice,
		arg.IsOnline,
		arg.Point,
		arg.Point_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSessionTokenPush = `-- name: UpdateSessionTokenPush :execrows
UPDATE session
SET "tokenPush" = $3, "updateAt" = now()
WHERE "userId" = $1 AND "idDevice" = $2
`

type UpdateSessionTokenPushParams struct {
	UserId    int32   `json:"userId"`
	IdDevice  string  `json:"idDevice"`
	TokenPush *string `json:"tokenPush"`
}

func (q *Queries) UpdateSessionTokenPush(ctx context.Context, arg UpdateSessionTokenPushParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSessionTokenPush, arg.UserId, arg.IdDevice, arg.TokenPush)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSessionsLocationByUser = `-- name: UpdateSessionsLocationByUser :exec
UPDATE session
SET location = point($2, $3), "updateAt" = now()
WHERE "userId" = $1
`

type UpdateSessionsLocationByUserParams struct {
	UserId  int32   `json:"userId"`
	Point   float64 `json:"point"`
	Point_2 float64 `json:"point_2"`
}

// Usado por el gateway de ubicacion (evento "l" de Socket.IO en la version
// NestJS): actualiza la ubicacion de todas las sesiones del usuario.
func (q *Queries) UpdateSessionsLocationByUser(ctx context.Context, arg UpdateSessionsLocationByUserParams) error {
	_, err := q.db.Exec(ctx, updateSessionsLocationByUser, arg.UserId, arg.Point, arg.Point_2)
	return err
}
