// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: store.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStore = `-- name: CreateStore :one
INSERT INTO store (name, address, contact, email, location, "companyId", "userId")
VALUES ($1, $2, $3, $4, point($5, $6), $7, $8)
RETURNING id, name, address, contact, email,
          "startupCost", "costKm", sales, "createdAt", "updatedAt",
          location[0]::float8 AS latitude,
          location[1]::float8 AS longitude,
          "companyId", "userId"
`

type CreateStoreParams struct {
	Name      string  `json:"name"`
	Address   string  `json:"address"`
	Contact   string  `json:"contact"`
	Email     string  `json:"email"`
	Point     float64 `json:"point"`
	Point_2   float64 `json:"point_2"`
	CompanyId *int32  `json:"companyId"`
	UserId    *int32  `json:"userId"`
}

type CreateStoreRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Address     string             `json:"address"`
	Contact     string             `json:"contact"`
	Email       string             `json:"email"`
	StartupCost float64            `json:"startupCost"`
	CostKm      float64            `json:"costKm"`
	Sales       int32              `json:"sales"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	Latitude    float64            `json:"latitude"`
	Longitude   float64            `json:"longitude"`
	CompanyId   *int32             `json:"companyId"`
	UserId      *int32             `json:"userId"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (CreateStoreRow, error) {
	row := q.db.QueryRow(ctx, createStore,
		arg.Name,
		arg.Address,
		arg.Contact,
		arg.Email,
		arg.Point,
		arg.Point_2,
		arg.CompanyId,
		arg.UserId,
	)
	var i CreateStoreRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Contact,
		&i.Email,
		&i.StartupCost,
		&i.CostKm,
		&i.Sales,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.CompanyId,
		&i.UserId,
	)
	return i, err
}

const getStoreByID = `-- name: GetStoreByID :one
SELECT id, name, address, contact, email, "startupCost", "costKm", sales,
       "createdAt", "updatedAt",
       location[0]::float8 AS latitude,
       location[1]::float8 AS longitude,
       "companyId", "userId"
FROM store
WHERE id = $1 AND "deletedAt" IS NULL
`

type GetStoreByIDRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Address     string             `json:"address"`
	Contact     string             `json:"contact"`
	Email       string             `json:"email"`
	StartupCost float64            `json:"startupCost"`
	CostKm      float64            `json:"costKm"`
	Sales       int32              `json:"sales"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	Latitude    float64            `json:"latitude"`
	Longitude   float64            `json:"longitude"`
	CompanyId   *int32             `json:"companyId"`
	UserId      *int32             `json:"userId"`
}

func (q *Queries) GetStoreByID(ctx context.Context, id int32) (GetStoreByIDRow, error) {
	row := q.db.QueryRow(ctx, getStoreByID, id)
	var i GetStoreByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Contact,
		&i.Email,
		&i.StartupCost,
		&i.CostKm,
		&i.Sales,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.CompanyId,
		&i.UserId,
	)
	return i, err
}

const listStoresByCompany = `-- name: ListStoresByCompany :many
SELECT id, name, address, contact, email, "startupCost", "costKm", sales,
       "createdAt", "updatedAt",
       location[0]::float8 AS latitude,
       location[1]::float8 AS longitude,
       "companyId", "userId"
FROM store
WHERE "companyId" = $1 AND "deletedAt" IS NULL
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListStoresByCompanyParams struct {
	CompanyId *int32 `json:"companyId"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type ListStoresByCompanyRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Address     string             `json:"address"`
	Contact     string             `json:"contact"`
	Email       string             `json:"email"`
	StartupCost float64            `json:"startupCost"`
	CostKm      float64            `json:"costKm"`
	Sales       int32              `json:"sales"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	Latitude    float64            `json:"latitude"`
	Longitude   float64            `json:"longitude"`
	CompanyId   *int32             `json:"companyId"`
	UserId      *int32             `json:"userId"`
}

func (q *Queries) ListStoresByCompany(ctx context.Context, arg ListStoresByCompanyParams) ([]ListStoresByCompanyRow, error) {
	rows, err := q.db.Query(ctx, listStoresByCompany, arg.CompanyId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoresByCompanyRow{}
	for rows.Next() {
		var i ListStoresByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Contact,
			&i.Email,
			&i.StartupCost,
			&i.CostKm,
			&i.Sales,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Latitude,
			&i.Longitude,
			&i.CompanyId,
			&i.UserId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoresByManager = `-- name: ListStoresByManager :many

SELECT s.id, s.name, s.address, s.contact, s.email,
       s."startupCost", s."costKm", s.sales, s."createdAt", s."updatedAt",
       s.location[0]::float8 AS latitude,
       s.location[1]::float8 AS longitude,
       c.id AS company_id, c.name AS company_name, c.address AS company_address,
       c.contact AS company_contact, c.image AS company_image,
       c.marker AS company_marker, c.email AS company_email,
       c."createdAt" AS company_created_at, c."updatedAt" AS company_updated_at,
       c.location[0]::float8 AS company_latitude,
       c.location[1]::float8 AS company_longitude,
       cc.id AS company_category_id,
       cc."updatedAt" AS company_category_updated_at,
       cat.id AS category_id, cat.name AS category_name,
       cat.image AS category_image,
       cat."createdAt" AS category_created_at,
       cat."updatedAt" AS category_updated_at
FROM store s
INNER JOIN company c ON c.id = s."companyId"
LEFT JOIN company_category cc ON cc."companyId" = c.id
LEFT JOIN category cat ON cat.id = cc."categoryId"
WHERE s."userId" = $1
ORDER BY s.id DESC, cc.id
`

type ListStoresByManagerRow struct {
	ID                       int32              `json:"id"`
	Name                     string             `json:"name"`
	Address                  string             `json:"address"`
	Contact                  string             `json:"contact"`
	Email                    string             `json:"email"`
	StartupCost              float64            `json:"startupCost"`
	CostKm                   float64            `json:"costKm"`
	Sales                    int32              `json:"sales"`
	CreatedAt                pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt                pgtype.Timestamptz `json:"updatedAt"`
	Latitude                 float64            `json:"latitude"`
	Longitude                float64            `json:"longitude"`
	CompanyID                int32              `json:"company_id"`
	CompanyName              string             `json:"company_name"`
	CompanyAddress           string             `json:"company_address"`
	CompanyContact           string             `json:"company_contact"`
	CompanyImage             string             `json:"company_image"`
	CompanyMarker            string             `json:"company_marker"`
	CompanyEmail             string             `json:"company_email"`
	CompanyCreatedAt         pgtype.Timestamptz `json:"company_created_at"`
	CompanyUpdatedAt         pgtype.Timestamptz `json:"company_updated_at"`
	CompanyLatitude          float64            `json:"company_latitude"`
	CompanyLongitude         float64            `json:"company_longitude"`
	CompanyCategoryID        *int32             `json:"company_category_id"`
	CompanyCategoryUpdatedAt pgtype.Timestamptz `json:"company_category_updated_at"`
	CategoryID               *int32             `json:"category_id"`
	CategoryName             *string            `json:"category_name"`
	CategoryImage            *string            `json:"category_image"`
	CategoryCreatedAt        pgtype.Timestamptz `json:"category_created_at"`
	CategoryUpdatedAt        pgtype.Timestamptz `json:"category_updated_at"`
}

// Tiendas. Usado por manager/store (listado con empresa y categorias) y por
// manager/enrollment (alta).
// Devuelve una fila por tienda/categoria; la API agrupa en Go. Equivale a
// storeRepository.find({ relations: { company: { categories: true } } }).
func (q *Queries) ListStoresByManager(ctx context.Context, userid *int32) ([]ListStoresByManagerRow, error) {
	rows, err := q.db.Query(ctx, listStoresByManager, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoresByManagerRow{}
	for rows.Next() {
		var i ListStoresByManagerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Contact,
			&i.Email,
			&i.StartupCost,
			&i.CostKm,
			&i.Sales,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Latitude,
			&i.Longitude,
			&i.CompanyID,
			&i.CompanyName,
			&i.CompanyAddress,
			&i.CompanyContact,
			&i.CompanyImage,
			&i.CompanyMarker,
			&i.CompanyEmail,
			&i.CompanyCreatedAt,
			&i.CompanyUpdatedAt,
			&i.CompanyLatitude,
			&i.CompanyLongitude,
			&i.CompanyCategoryID,
			&i.CompanyCategoryUpdatedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryImage,
			&i.CategoryCreatedAt,
			&i.CategoryUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteStore = `-- name: SoftDeleteStore :execrows
UPDATE store SET "deletedAt" = now() WHERE id = $1 AND "deletedAt" IS NULL
`

func (q *Queries) SoftDeleteStore(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteStore, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStore = `-- name: UpdateStore :one
UPDATE store
SET name = $2, address = $3, contact = $4, email = $5,
    location = point($6, $7), "deletedAt" = NULL, "updatedAt" = now()
WHERE id = $1 AND "deletedAt" IS NULL
RETURNING id, name, address, contact, email, "startupCost", "costKm", sales,
          "createdAt", "updatedAt",
          location[0]::float8 AS latitude,
          location[1]::float8 AS longitude,
          "companyId", "userId"
`

type UpdateStoreParams struct {
	ID      int32   `json:"id"`
	Name    string  `json:"name"`
	Address string  `json:"address"`
	Contact string  `json:"contact"`
	Email   string  `json:"email"`
	Point   float64 `json:"point"`
	Point_2 float64 `json:"point_2"`
}

type UpdateStoreRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Address     string             `json:"address"`
	Contact     string             `json:"contact"`
	Email       string             `json:"email"`
	StartupCost float64            `json:"startupCost"`
	CostKm      float64            `json:"costKm"`
	Sales       int32              `json:"sales"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	Latitude    float64            `json:"latitude"`
	Longitude   float64            `json:"longitude"`
	CompanyId   *int32             `json:"companyId"`
	UserId      *int32             `json:"userId"`
}

// UpdateStoreDto solo permite name, address, contact, email y location.
func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) (UpdateStoreRow, error) {
	row := q.db.QueryRow(ctx, updateStore,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Contact,
		arg.Email,
		arg.Point,
		arg.Point_2,
	)
	var i UpdateStoreRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Contact,
		&i.Email,
		&i.StartupCost,
		&i.CostKm,
		&i.Sales,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.CompanyId,
		&i.UserId,
	)
	return i, err
}
