// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO "user" ("idGoogle", "fullName", email, phone, password, image, roles)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, "idGoogle", "fullName", email, phone, image, "isActive", roles, "createdAt", "updatedAt"
`

type CreateUserParams struct {
	IdGoogle *string  `json:"idGoogle"`
	FullName string   `json:"fullName"`
	Email    string   `json:"email"`
	Phone    *string  `json:"phone"`
	Password string   `json:"password"`
	Image    string   `json:"image"`
	Roles    []string `json:"roles"`
}

type CreateUserRow struct {
	ID        int32              `json:"id"`
	IdGoogle  *string            `json:"idGoogle"`
	FullName  string             `json:"fullName"`
	Email     string             `json:"email"`
	Phone     *string            `json:"phone"`
	Image     string             `json:"image"`
	IsActive  bool               `json:"isActive"`
	Roles     []string           `json:"roles"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

// Consultas sobre "user". El password y passwordTemporary nunca se devuelven
// al cliente: solo se seleccionan en las consultas de autenticacion.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.IdGoogle,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.Image,
		arg.Roles,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.IdGoogle,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Image,
		&i.IsActive,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAuthByEmail = `-- name: GetUserAuthByEmail :one
SELECT id, email, password, "passwordTemporary", "fullName", phone, image, "isActive", roles
FROM "user"
WHERE email = $1
`

type GetUserAuthByEmailRow struct {
	ID                int32    `json:"id"`
	Email             string   `json:"email"`
	Password          string   `json:"password"`
	PasswordTemporary *string  `json:"passwordTemporary"`
	FullName          string   `json:"fullName"`
	Phone             *string  `json:"phone"`
	Image             string   `json:"image"`
	IsActive          bool     `json:"isActive"`
	Roles             []string `json:"roles"`
}

func (q *Queries) GetUserAuthByEmail(ctx context.Context, email string) (GetUserAuthByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthByEmail, email)
	var i GetUserAuthByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PasswordTemporary,
		&i.FullName,
		&i.Phone,
		&i.Image,
		&i.IsActive,
		&i.Roles,
	)
	return i, err
}

const getUserByEmailOrPhone = `-- name: GetUserByEmailOrPhone :one
SELECT id, email, phone
FROM "user"
WHERE email = $1 OR phone = $2
LIMIT 1
`

type GetUserByEmailOrPhoneParams struct {
	Email string  `json:"email"`
	Phone *string `json:"phone"`
}

type GetUserByEmailOrPhoneRow struct {
	ID    int32   `json:"id"`
	Email string  `json:"email"`
	Phone *string `json:"phone"`
}

func (q *Queries) GetUserByEmailOrPhone(ctx context.Context, arg GetUserByEmailOrPhoneParams) (GetUserByEmailOrPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailOrPhone, arg.Email, arg.Phone)
	var i GetUserByEmailOrPhoneRow
	err := row.Scan(&i.ID, &i.Email, &i.Phone)
	return i, err
}

const getUserByEmailOrPhoneExcludingID = `-- name: GetUserByEmailOrPhoneExcludingID :one
SELECT id, email, phone
FROM "user"
WHERE (email = $1 OR phone = $2) AND id <> $3
LIMIT 1
`

type GetUserByEmailOrPhoneExcludingIDParams struct {
	Email string  `json:"email"`
	Phone *string `json:"phone"`
	ID    int32   `json:"id"`
}

type GetUserByEmailOrPhoneExcludingIDRow struct {
	ID    int32   `json:"id"`
	Email string  `json:"email"`
	Phone *string `json:"phone"`
}

func (q *Queries) GetUserByEmailOrPhoneExcludingID(ctx context.Context, arg GetUserByEmailOrPhoneExcludingIDParams) (GetUserByEmailOrPhoneExcludingIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailOrPhoneExcludingID, arg.Email, arg.Phone, arg.ID)
	var i GetUserByEmailOrPhoneExcludingIDRow
	err := row.Scan(&i.ID, &i.Email, &i.Phone)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, "idGoogle", "fullName", email, phone, image, "isActive", roles, "createdAt", "updatedAt"
FROM "user"
WHERE id = $1
`

type GetUserByIDRow struct {
	ID        int32              `json:"id"`
	IdGoogle  *string            `json:"idGoogle"`
	FullName  string             `json:"fullName"`
	Email     string             `json:"email"`
	Phone     *string            `json:"phone"`
	Image     string             `json:"image"`
	IsActive  bool               `json:"isActive"`
	Roles     []string           `json:"roles"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.IdGoogle,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Image,
		&i.IsActive,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserNameByEmail = `-- name: GetUserNameByEmail :one
SELECT id, "fullName"
FROM "user"
WHERE email = $1
`

type GetUserNameByEmailRow struct {
	ID       int32  `json:"id"`
	FullName string `json:"fullName"`
}

func (q *Queries) GetUserNameByEmail(ctx context.Context, email string) (GetUserNameByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserNameByEmail, email)
	var i GetUserNameByEmailRow
	err := row.Scan(&i.ID, &i.FullName)
	return i, err
}

const setTemporaryPassword = `-- name: SetTemporaryPassword :execrows
UPDATE "user"
SET "passwordTemporary" = $2, "updatedAt" = now()
WHERE email = $1
`

type SetTemporaryPasswordParams struct {
	Email             string  `json:"email"`
	PasswordTemporary *string `json:"passwordTemporary"`
}

func (q *Queries) SetTemporaryPassword(ctx context.Context, arg SetTemporaryPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTemporaryPassword, arg.Email, arg.PasswordTemporary)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserGoogleID = `-- name: UpdateUserGoogleID :execrows
UPDATE "user"
SET "idGoogle" = $2, "updatedAt" = now()
WHERE email = $1
`

type UpdateUserGoogleIDParams struct {
	Email    string  `json:"email"`
	IdGoogle *string `json:"idGoogle"`
}

func (q *Queries) UpdateUserGoogleID(ctx context.Context, arg UpdateUserGoogleIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserGoogleID, arg.Email, arg.IdGoogle)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE "user"
SET password = $2, "updatedAt" = now()
WHERE id = $1
RETURNING id, "idGoogle", "fullName", email, phone, image, "isActive", roles, "createdAt", "updatedAt"
`

type UpdateUserPasswordParams struct {
	ID       int32  `json:"id"`
	Password string `json:"password"`
}

type UpdateUserPasswordRow struct {
	ID        int32              `json:"id"`
	IdGoogle  *string            `json:"idGoogle"`
	FullName  string             `json:"fullName"`
	Email     string             `json:"email"`
	Phone     *string            `json:"phone"`
	Image     string             `json:"image"`
	IsActive  bool               `json:"isActive"`
	Roles     []string           `json:"roles"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (UpdateUserPasswordRow, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.Password)
	var i UpdateUserPasswordRow
	err := row.Scan(
		&i.ID,
		&i.IdGoogle,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Image,
		&i.IsActive,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE "user"
SET "fullName" = $2, email = $3, phone = $4, image = $5, "updatedAt" = now()
WHERE id = $1
RETURNING id, "idGoogle", "fullName", email, phone, image, "isActive", roles, "createdAt", "updatedAt"
`

type UpdateUserProfileParams struct {
	ID       int32   `json:"id"`
	FullName string  `json:"fullName"`
	Email    string  `json:"email"`
	Phone    *string `json:"phone"`
	Image    string  `json:"image"`
}

type UpdateUserProfileRow struct {
	ID        int32              `json:"id"`
	IdGoogle  *string            `json:"idGoogle"`
	FullName  string             `json:"fullName"`
	Email     string             `json:"email"`
	Phone     *string            `json:"phone"`
	Image     string             `json:"image"`
	IsActive  bool               `json:"isActive"`
	Roles     []string           `json:"roles"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Image,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.IdGoogle,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Image,
		&i.IsActive,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
